import sys
from pathlib import Path
from reportlab.platypus import SimpleDocTemplate,Paragraph,Spacer,KeepTogether,Table,TableStyle
from reportlab.lib.styles import getSampleStyleSheet,ParagraphStyle
from reportlab.lib.colors import HexColor
from reportlab.lib.enums import TA_LEFT
import pymupdf
OUT=Path('public/downloads');OUT.mkdir(parents=True,exist_ok=True)
styles=getSampleStyleSheet()
styles.add(ParagraphStyle(name='Brand',fontName='Helvetica-Bold',fontSize=10,textColor=HexColor('#ce5b32'),spaceAfter=18))
styles.add(ParagraphStyle(name='TitleM',fontName='Times-Roman',fontSize=29,leading=32,textColor=HexColor('#173f36'),spaceAfter=20))
styles.add(ParagraphStyle(name='BodyM',fontName='Helvetica',fontSize=10,leading=15,textColor=HexColor('#314b40'),spaceAfter=12))
styles.add(ParagraphStyle(name='HeadingM',fontName='Helvetica-Bold',fontSize=12,leading=16,textColor=HexColor('#173f36'),spaceBefore=10,spaceAfter=8))
def footer(canvas,doc):
 canvas.setStrokeColor(HexColor('#d9dfd4'));canvas.line(48,45,547,45);canvas.setFont('Helvetica',8);canvas.setFillColor(HexColor('#536259'));canvas.drawString(48,30,'Jerry Bannister Zachary | Independent proposal | Fictional demonstration');canvas.drawRightString(547,30,str(doc.page))
def build(name,title,sections):
 story=[Paragraph('IMPACT MOSAIC / AI FOR INCLUSIVE OPPORTUNITY',styles['Brand']),Paragraph(title,styles['TitleM'])]
 for heading,text in sections:
  story.append(KeepTogether([Paragraph(heading,styles['HeadingM']),Paragraph(text,styles['BodyM'])]))
 SimpleDocTemplate(str(OUT/name),pagesize=(595,842),rightMargin=48,leftMargin=48,topMargin=45,bottomMargin=65).build(story,onFirstPage=footer,onLaterPages=footer)
def build_introduction():
 compact=ParagraphStyle('IntroCompact',parent=styles['BodyM'],fontSize=8.5,leading=11,spaceAfter=7)
 heading=ParagraphStyle('IntroHeading',parent=styles['HeadingM'],fontSize=10,leading=13,spaceBefore=7,spaceAfter=5)
 title=ParagraphStyle('IntroTitle',parent=styles['TitleM'],fontSize=27,leading=29,spaceAfter=10)
 brand=ParagraphStyle('IntroBrand',parent=styles['Brand'],spaceAfter=10)
 cell_head=ParagraphStyle('IntroCellHead',parent=heading,fontSize=8,leading=10,spaceBefore=0,spaceAfter=0,textColor=HexColor('#b64d2c'))
 cell_body=ParagraphStyle('IntroCellBody',parent=compact,fontSize=8,leading=10.3,spaceAfter=0)
 chapters=[
  ('01 MOBILITY','In Otukpo, NCPWD, Beautiful Gate and Senator Abba Moro collaborated on mobility-device distribution. Gufwan spoke at the event; no independently verified totals or outcomes are asserted.', 'https://qualitativemagazine.com/ncpwd-beautiful-gate-foundation-senator-abba-moro-empower-pwds-in-benue-with-thousands-of-tricycles-and-assistive-devices/'),
  ('02 LIVELIHOODS','Farming inputs were distributed through disability associations, with Lawrence Idemudia representing Gufwan. Published 7 July 2025; the report gives a conflicting June activity date.', 'https://fmino.gov.ng/empowering-persons-with-disabilities-in-agriculture-ncpwd-distributes-fertilizers-and-farming-tools/'),
  ('03 EDUCATION','At UBEC on 26 September 2024, Gufwan advocated for inclusive education, assistive materials and support for girls with disabilities. This is advocacy; materials delivery is unverified.', 'https://fmino.gov.ng/children-with-disabilities-deserve-more-attention-to-attain-their-aspirations-in-life-ayuba-gufwan/'),
  ('04 CIVIC RIGHTS','NCPWD monitored Edo and Kwara elections on 21 September 2024. The report records participation alongside an access barrier in Edo and violence restricting voting in Kwara.', 'https://fmino.gov.ng/persons-with-disabilities-franchise-can-never-be-undermined-gufwan/'),
  ('05 COMMUNITIES','Gufwan advocated for a Southeast office in Abia; Governor Alex Otti approved a facility. The report, published 19 January 2025, does not establish that the office is operational.', 'https://fmino.gov.ng/gufwan-takes-governor-otti-as-champion-of-the-disabilities-community-in-nigeria/'),
  ('06 ENFORCEMENT','A 14 June 2025 report describes NCPWD and Nightstone Global training security personnel. It credits Gufwan with the keynote and explicitly names Ikem Ochigbelam as his representative.', 'https://fmino.gov.ng/national-commission-for-persons-with-disabilities-organises-capacity-building-training-for-security-agencies-on-accessibility-and-anti-discrimination-enforcement/'),
  ('07 HEALTH','The 18 December 2025 Karonmajiji outreach credits TLM, CHAI, CBM and Sightsavers. Lawrence Idemudia represented Gufwan. Wider medical provision was a plan; sustained health outcomes are unverified.', 'https://fmino.gov.ng/ncpwd-embarks-on-medical-outreach-treats-over-150-with-various-medical-conditions/'),
  ('08 INSTITUTIONS','CBM engagement on 31 October 2024 proposed deeper cooperation. NOA engagement in December 2025 and the May 2026 NDMIS workshop support coordination; database deployment is unverified.', 'https://fmino.gov.ng/gufwan-visits-christian-blind-mission-to-strengthen-ties-for-inclusivity/'),
 ]
 flow=[Paragraph('IMPACT MOSAIC / DISABILITY INCLUSION',brand),Paragraph('Building a more inclusive Nigeria',title),Paragraph('Leadership, partners and persons with disabilities are already at work. This independent demonstration presents eight documented chapters, a full-frame source-linked photo gallery and ideas for accessible digital support.',compact),Paragraph('Leadership and a public mandate',heading),Paragraph('President Bola Ahmed Tinubu appointed Ayuba Gufwan Executive Secretary of NCPWD on <link href="https://statehouse.gov.ng/president-tinubu-appoints-new-heads-of-agencies-and-programmes-under-the-federal-ministry-of-humanitarian-affairs-disaster-management-and-social-management/" color="#173f36">6 August 2024</link>. Reports distinguish his direct engagements from work carried out by representatives and partners. They do not imply endorsement of this demo.',compact)]
 rows=[[Paragraph(label,cell_head),Paragraph(f'{text} <link href="{url}" color="#173f36"><u>Source</u></link>',cell_body)] for label,text,url in chapters]
 table=Table(rows,colWidths=[96,415],hAlign='LEFT')
 table.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,-1),HexColor('#f3f5ee')),('BOX',(0,0),(-1,-1),0.5,HexColor('#d9dfd4')),('INNERGRID',(0,0),(-1,-1),0.4,HexColor('#d9dfd4')),('VALIGN',(0,0),(-1,-1),'TOP'),('LEFTPADDING',(0,0),(-1,-1),7),('RIGHTPADDING',(0,0),(-1,-1),7),('TOPPADDING',(0,0),(-1,-1),6),('BOTTOMPADDING',(0,0),(-1,-1),6)]))
 flow += [table,Paragraph('Five ideas to explore with AI',heading),Paragraph('Accessibility; agriculture; employment; NDMIS and data quality; zonal coordination. These are proposals for human-led pilots. A fictional learner, expert consultant and intermediary sandbox demonstrates learning, practical feedback and follow-up.',compact),Paragraph('A conversation about one co-designed pilot',heading),Paragraph('I am Jerry Bannister Zachary, a statistician and a person with a disability. I would welcome the opportunity to contribute my technical skills. Participant safeguards, accessible delivery and evaluation would be agreed before a real pilot; no live NCPWD or NDMIS connection is assumed.',compact),Paragraph('Further institutional sources: <link href="https://fmino.gov.ng/ncpwd-strengthens-collaboration-with-national-orientation-agency-to-deepen-national-disability-inclusion/" color="#173f36">NOA, 10 Dec 2025</link> | <link href="https://ossaposneo.org/brief-report-of-the-3-day-stakeholders-consultative-workshop-on-the-development-of-the-national-disability-management-information-system-ndmis/" color="#173f36">NDMIS workshop, May 2026</link>. Publication dates and reported activity dates are distinguished on the website.',ParagraphStyle('IntroSources',parent=compact,fontSize=7,leading=9,spaceAfter=0))]
 SimpleDocTemplate(str(OUT/'introduction.pdf'),pagesize=(595,842),rightMargin=42,leftMargin=42,topMargin=30,bottomMargin=56).build(flow,onFirstPage=footer,onLaterPages=footer)
build_introduction()
if "--include-proposal" in sys.argv:
 build('partnership-proposal.pdf','A small pilot.<br/>A stronger evidence base.',[
 ('The proposed partnership','Jerry Bannister Zachary offers to develop and evaluate accessible AI tools with NCPWD leadership, persons with disabilities, experts and local intermediaries. Leadership selects the priority; the demonstration supports a conversation rather than assuming endorsement.'),
 ('The problem and response','People can face fragmented information, inaccessible learning materials and slow follow-up. Impact Mosaic demonstrates one linked journey: fictional profile, recommendations, enrolment, lessons, assessment, practical feedback, demonstrated skills and mentoring. Intermediaries can assist at the learner\'s request.'),
 ('Five opportunities to test','Accessibility: document explanations and support enquiries. Agriculture: reviewed training and extension questions. Employment: skills-based discovery and accommodation enquiries. NDMIS: authorised data-quality assistance. Zonal coordination: maintained human-support routing. Dependencies include dated sources, accessible resources and responsible staff.'),
 ('Suggested 8-week pilot','Weeks 1-2: agree one use case, co-design with PWD participants, verify materials, accessibility and consent. Weeks 3-6: support 20 consenting learners through courses and expert follow-up. Weeks 7-8: analyse completion, support response and participant feedback. These are proposed parameters, not commitments or projected outcomes.'),
 ('Evaluation','Record invitations, enrolments, active participation, lesson completion, quiz attempts and scores, practical assessment approval, mentoring requests, unresolved requests and time to first response. Report counts and denominators, dropouts and access barriers. Use baseline and endline practical tasks with a consistent expert rubric. Employment, income and longer-term wellbeing require separate later follow-up; learning gains alone do not establish causal economic impact.'),
 ('Technical and access approach','React, TypeScript and Vite on Cloudflare Pages. A server-side Worker calls Groq with bounded non-identifying context and validates source IDs. A persistent global free-budget limiter caps AI requests. Courses and expert support work without AI. English, Hausa, Yoruba and Igbo support is experimental outside reviewed English originals. Text size, keyboard access, reduced motion, transcripts and suitable device read-aloud support access.'),
 ('Data and accountability','Current records are fictional and isolated in the visitor\'s tab session, with reset and export. Real accounts or durable personal data require an authorised pilot, consent, role-based access, retention rules, safeguards and trained staff. NDMIS integration requires the system owner\'s authorisation, verified interfaces and an agreed schema. No identifying record is sent to the AI provider by the application.'),
 ('Free-service constraints','No paid services are proposed. This demonstration reserves at most one AI call per minute and 20 per UTC day across the whole site. Free allowances can change and are not service guarantees. Missing credentials, quota or provider outages produce a clear error while learning stays usable.'),
 ('Leadership decisions','Choose one pilot area and a responsible coordinator. Confirm participant recruitment, accessible delivery, expert capacity, language review and evaluation resources. Agree the governance and support arrangements before real participant records are introduced.'),
 ('Reviewed evidence: 4 October 2026','<link href="https://fmino.gov.ng/ncpwd-amnesty-international-to-collaborate-on-skills-acquisition-inclusion-programs-for-persons-with-disabilities/">FMINO: NCPWD-Amnesty skills collaboration, 7 November 2025</link>.<br/><link href="https://ossaposneo.org/brief-report-of-the-3-day-stakeholders-consultative-workshop-on-the-development-of-the-national-disability-management-information-system-ndmis/">OSSAP-SNEO: NDMIS workshop report, 22 May 2026</link>.<br/><link href="https://console.groq.com/docs/rate-limits">Groq: current free-plan rate limits</link>. These sources establish programme context and technical constraints, not platform outcomes.')])
render=Path('output/pdf');render.mkdir(parents=True,exist_ok=True)
for filename in (['introduction.pdf', 'partnership-proposal.pdf'] if '--include-proposal' in sys.argv else ['introduction.pdf']):
 doc=pymupdf.open(OUT/filename);print(filename,len(doc),'pages')
 for i,page in enumerate(doc):page.get_pixmap(matrix=pymupdf.Matrix(1.2,1.2)).save(str(render/(filename.replace('.pdf','')+f'-{i+1}.png')))
