import { useEffect, useRef, useState, type FormEvent } from 'react';
import type { Course } from './catalogue';
import { courses as seedCourses } from './catalogue';
import type { SharedDemoSession } from './sharedDemo';
import { skillCategories } from './skillCategories';
import { demoDate } from './administratorMetrics';
import { courseCoordinationStatus, coursePublishIssues, currentAssignment, type CourseDecisionInput, type LearningAssignmentInput, type CourseDraftInput } from './coordinationDemo';

export type CoordinationCallbacks = {
 onCourseDecision: (input: CourseDecisionInput) => string | undefined;
 onAssignment: (input: LearningAssignmentInput) => string | undefined;
 onCourseDraft: (input: CourseDraftInput) => string | undefined;
};
type CoordinationView = 'Trainer roster' | 'Courses' | 'Learning oversight';
const text = (f: FormData, key: string) => String(f.get(key) || '').trim();

export function AdministratorCoordination({ session, view, ...actions }: CoordinationCallbacks & { session: SharedDemoSession; view: CoordinationView }) {
 const [search, setSearch] = useState('');
 const [filter, setFilter] = useState('all');
 const [opened, setOpened] = useState<{ course: Course; revision: number }>();
 const [editing, setEditing] = useState(false);
 const [error, setError] = useState('');
 const [notice, setNotice] = useState('');
 const feedback = useRef<HTMLParagraphElement>(null);
 const title = useRef<HTMLHeadingElement>(null);
 useEffect(() => { if (error) feedback.current?.focus(); }, [error]);
 useEffect(() => { if (opened || editing) title.current?.focus(); }, [opened?.course.id, editing]);
 const roster = session.reviews?.roster ?? [];
 const matches = (value: string) => value.toLowerCase().includes(search.trim().toLowerCase());
 function result(message: string | undefined, success: string) { setError(message || ''); setNotice(message ? '' : success); return !message; }
 function open(course: Course) { setOpened({ course: structuredClone(course), revision: session.recordMetadata[`course:${course.id}`].revision }); setEditing(false); setError(''); setNotice(''); }
 const status = <><p role="status">{notice}</p>{error && <p role="alert" className="mp-error" tabIndex={-1} ref={feedback}>{error}</p>}</>;
 const searchField = <label className="mp-field">Search {view.toLowerCase()}<input type="search" value={search} onChange={e => setSearch(e.target.value)} /></label>;
 function assignment(kind: 'course' | 'enrolment' | 'question', recordId: string, submissionId?: string, canAssign = true) {
  const assigned = currentAssignment(session, kind, recordId);
  const revision = kind === 'course' && opened?.course.id === recordId ? opened.revision : session.recordMetadata[`${kind}:${recordId}`]?.revision;
  return <section className="ma-assignment"><h4>{kind === 'course' ? 'Course reviewer' : 'Learning reviewer'}</h4>
   {assigned ? <p>{assigned.stale ? 'Earlier assignment · evidence changed; assign the latest evidence.' : 'Assigned for this revision.'} {roster.find(r => r.id === assigned.assignment.rosterId)?.skill} · {assigned.assignment.reviewer} · {demoDate(assigned.assignment.at)}<br />{assigned.assignment.suitabilityNote}</p> : <p>No reviewer assigned.</p>}
   {!canAssign ? <p>Trainer action recorded. Prior coordination remains in the history.</p> : !roster.length ? <p>Approve a trainer application before assigning a demo reviewer.</p> : <form key={`${recordId}:${revision}:${submissionId}`} onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); result(actions.onAssignment({ kind, recordId, expectedRevision: revision!, expectedAssignmentId: assigned?.assignment.id, rosterId: text(f, 'roster'), suitabilityNote: text(f, 'suitability'), reason: text(f, 'reason'), reviewer: text(f, 'reviewer'), submissionId }), 'Reviewer assignment recorded.'); }}>
    <label className="mp-field">Demo reviewer<select name="roster" required>{roster.map(r => <option key={r.id} value={r.id}>{session.user.profile.name} · {r.skill}</option>)}</select></label>
    <label className="mp-field">Suitability and access approach<textarea name="suitability" required maxLength={5000} rows={3} /></label>
    <p>Describe why this person suits this task and the learner’s access preferences. Foundation completion alone does not establish specialist trade-assessment competence.</p>
    <label className="mp-field">Assignment reason<textarea name="reason" required maxLength={5000} rows={2} /></label><label className="mp-field">Assignment reviewer label<input name="reviewer" required maxLength={250} defaultValue="Demo administrator" /></label><button>Assign demo reviewer</button>
   </form>}
  <details><summary>Reviewer assignment history</summary>{(session.coordination?.assignments ?? []).filter(a => a.kind === kind && a.recordId === recordId).map(a => <article className="ma-question" key={a.id}><p>{a.reviewer} · {demoDate(a.at)}</p><p>{a.suitabilityNote}</p><p>{a.reason}</p></article>)}</details>
  </section>;
 }
 if (view === 'Trainer roster') {
  const visible = roster.filter(r => matches(`${session.user.profile.name} ${r.skill}`));
  return <>{status}<p>Approved applications create a simulated mentoring roster. Entries do not verify qualifications or open a facilitator account.</p>{searchField}<p role="status">{visible.length} roster entries shown.</p>{!visible.length && <section className="mp-card"><h3>{roster.length ? 'No matching trainers' : 'No approved trainers yet'}</h3><p>Review a trainer application and approve all four criteria to add its applicant here.</p></section>}{visible.map(r => {
   const decision = session.reviews!.decisions.find(d => d.id === r.decisionId)!;
   const snapshot = session.submissions.find(s => s.id === decision.submissionId)!;
   const evidence = snapshot.payload as { examples: string; explanation: string; accessibility: string };
   return <article className="mp-card" key={r.id}><h3>{session.user.profile.name}</h3><p><strong>{r.skill}</strong> · Demo mentoring only</p><p>Approved by {decision.reviewer} · {demoDate(r.approvedAt)}</p><p>{decision.reason}</p><details><summary>Reviewed teaching evidence and access approach</summary><p className="mp-work">{evidence.examples}</p><p className="mp-work">{evidence.explanation}</p><p className="mp-work">{evidence.accessibility}</p></details></article>;
  })}</>;
 }
 if (view === 'Learning oversight') {
  const work = session.user.learning.enrolments.filter(e => e.submitted && matches(`${session.user.profile.name} ${(e.courseVersion ?? session.user.learning.courses.find(c => c.id === e.courseId))?.title}`) && (filter === 'all' || (filter === 'pending' ? !e.approved : e.approved)));
  const questions = session.user.learning.requests.filter(q => q.kind === 'question' && matches(`${session.user.profile.name} ${q.text}`) && (filter === 'all' || (filter === 'pending' ? !q.reply : !!q.reply)));
  return <>{status}<p>Coordinate submitted practical work and learning questions. Trainers assess and reply through the labelled User demo controls while the Facilitator interface is deferred.</p><div className="ma-filters">{searchField}<label>Learning status<select value={filter} onChange={e => setFilter(e.target.value)}><option value="all">All learning records</option><option value="pending">Awaiting trainer action</option><option value="done">Trainer action recorded</option></select></label></div><p role="status">{work.length} practical submissions · {questions.length} learning questions shown.</p>
   {!work.length && !questions.length && <section className="mp-card"><h3>No matching learning records</h3><p>Submit practical work or a question in User to coordinate its review here.</p></section>}
   {work.map(e => { const c = e.courseVersion ?? session.user.learning.courses.find(c => c.id === e.courseId)!; const snapshot = session.submissions.filter(s => s.kind === 'work' && s.recordId === e.id).at(-1); return <article className="mp-card" key={e.id}><h3>{c.title} · Practical work</h3><p>{session.user.profile.name} · {e.approved ? 'Sample trainer approval recorded' : 'Pending trainer assessment'}</p>{c.delivery === 'foundation' && <p className="ma-foundation">Foundation plan or role play only. Observed trade competence is not assessed.</p>}<details><summary>Submitted work and feedback</summary><p className="mp-work">{e.submitted}</p><p>{e.feedback || 'No trainer feedback recorded.'}</p></details>{assignment('enrolment', e.id, snapshot?.id, !e.approved)}</article>; })}
   {questions.map(q => <article className="mp-card" key={q.id}><h3>Learning question</h3><p>{session.user.profile.name} · {session.user.learning.courses.find(c => c.id === q.courseId)?.title}</p><p className="mp-work">{q.text}</p><p>{q.reply || 'Awaiting trainer reply.'}</p>{assignment('question', q.id, undefined, !q.reply)}</article>)}
  </>;
 }
 const visible = session.user.learning.courses.filter(c => matches(c.title + ' ' + c.description) && (filter === 'all' || courseCoordinationStatus(session, c.id) === filter));
 const latest = opened && session.user.learning.courses.find(c => c.id === opened.course.id);
 const stale = opened && session.recordMetadata[`course:${opened.course.id}`]?.revision !== opened.revision;
 if (editing) return <>{status}<button onClick={() => setEditing(false)}>Back to courses</button><h3 ref={title} tabIndex={-1}>{opened ? 'Revise demo course' : 'Prepare demo course draft'}</h3><CourseEditor course={opened?.course} roster={roster} onSave={(course, accessibilityEvidence, reason, reviewer) => { const saved = result(actions.onCourseDraft({ course, expectedRevision: opened?.revision ?? null, accessibilityEvidence, reason, reviewer }), 'Demo draft saved for course review.'); if (saved) { setEditing(false); setOpened(undefined); } }} /></>;
 return <>{status}<p>Preview content, coordinate review and manage availability. Existing enrolments keep their course version when content changes or a course is archived.</p>{!opened ? <><button className="primary" disabled={!roster.length} onClick={() => { setEditing(true); setError(''); setNotice(''); }}>Prepare demo course draft</button>{!roster.length && <p>Approve a trainer application before preparing an authored demo course.</p>}<div className="ma-filters">{searchField}<label>Course status<select value={filter} onChange={e => setFilter(e.target.value)}>{['all','draft','review','needs-changes','published','archived'].map(s => <option key={s} value={s}>{s === 'all' ? 'All course statuses' : s}</option>)}</select></label></div><p role="status">{visible.length} courses shown.</p>{!visible.length && <p>No matching courses. Change the search or status filter.</p>}{visible.map(c => <article className="ma-course" key={c.id}><h3>{c.title}</h3><p>{courseCoordinationStatus(session, c.id)} · {c.lessons.length} lessons · {c.quiz.length} quiz questions</p><p>{c.description}</p><button onClick={() => open(c)}>Review course: {c.title}</button></article>)}</> : <>
  <button onClick={() => { setOpened(undefined); setError(''); }}>Back to courses</button><h3 ref={title} tabIndex={-1}>{opened.course.title}</h3><p>{latest && courseCoordinationStatus(session, latest.id)} · Content revision {opened.revision}</p>{stale && <div className="mp-error"><p role="alert">Course content changed. Review its latest version before deciding.</p><button onClick={() => latest && open(latest)}>Open latest course version</button></div>}
  <CoursePreview course={opened.course} />{!seedCourses.some(c => c.id === opened.course.id) && <button onClick={() => setEditing(true)}>Revise demo course</button>}
  {assignment('course', opened.course.id)}
  <form className="mp-card" key={`${opened.course.id}:${opened.revision}`} onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); result(actions.onCourseDecision({ courseId: opened.course.id, expectedRevision: opened.revision, outcome: text(f, 'outcome') as CourseDecisionInput['outcome'], reason: text(f, 'reason'), reviewer: text(f, 'reviewer'), accessibilityEvidence: text(f, 'accessibility') || undefined }), 'Course decision recorded.'); }}><h3>Course availability decision</h3><p>Publishing requires complete content and accessible delivery evidence. Authored courses also require an approved demo trainer author.</p>{coursePublishIssues(session, opened.course, session.coordination?.drafts?.filter(d => d.course.id === opened.course.id).at(-1)?.accessibilityEvidence).length > 0 && <ul>{coursePublishIssues(session, opened.course, session.coordination?.drafts?.filter(d => d.course.id === opened.course.id).at(-1)?.accessibilityEvidence).map(issue => <li key={issue}>{issue}</li>)}</ul>}
   <label className="mp-field">Course outcome<select name="outcome" aria-label="Course outcome"><option value="needs-changes">Needs changes</option><option value="publish">Publish / restore availability</option><option value="archive">Archive for new enrolments</option></select></label><label className="mp-field">Accessible delivery review<textarea name="accessibility" maxLength={5000} rows={3} defaultValue={session.coordination?.drafts?.filter(d => d.course.id === opened.course.id).at(-1)?.accessibilityEvidence} /></label><label className="mp-field">Course decision reason<textarea name="reason" required maxLength={5000} rows={3} /></label><label className="mp-field">Course reviewer label<input name="reviewer" required maxLength={250} defaultValue="Demo administrator" /></label><button className="primary" disabled={!!stale}>Record course decision</button>
  </form><details><summary>Course decision history</summary>{(session.coordination?.courseDecisions ?? []).filter(d => d.courseId === opened.course.id).map(d => <article className="ma-question" key={d.id}><h4>{d.outcome} · Revision {d.expectedRevision}</h4><p>{d.reviewer} · {demoDate(d.at)}</p><p>{d.reason}</p><details><summary>Reviewed course content</summary><CoursePreview course={d.courseVersion} /></details></article>)}</details>
 </>}</>;
}

function CoursePreview({ course: c }: { course: Course }) {
 return <section className="mp-card"><p>{c.description}</p><p>Skills: {c.skills.join(', ')}</p><p>Delivery: {c.delivery ?? 'self-paced'} · Tools: {c.tools?.join(', ') || 'None specified'}</p>{c.outcome && <p>{c.outcome}</p>}{c.delivery === 'foundation' && <p className="ma-foundation">Written foundation learning. No observed trade competence or supervised workshop is certified.</p>}<details><summary>Preview lessons ({c.lessons.length})</summary>{c.lessons.map((l, i) => <article className="ma-question" key={i}><h4>{i + 1}. {l.title}</h4><p className="mp-work">{l.body}</p>{l.resource && <p>{l.resource}</p>}{l.video && <p>Video reference: {l.video}</p>}{l.transcript && <p className="mp-work">Transcript: {l.transcript}</p>}</article>)}</details><details><summary>Preview quiz and correct answers ({c.quiz.length})</summary>{c.quiz.map((q,i) => <article key={i}><h4>{q.question}</h4><ol>{q.options.map((o,j) => <li key={j}>{o}{q.answer === j ? ' · Correct answer' : ''}</li>)}</ol></article>)}</details><h4>Practical assignment</h4><p className="mp-work">{c.assignment}</p></section>;
}

function CourseEditor({ course, roster, onSave }: { course?: Course; roster: NonNullable<SharedDemoSession['reviews']>['roster']; onSave: (course: Course, access: string, reason: string, reviewer: string) => void }) {
 const [lessons, setLessons] = useState(course?.lessons ?? [{ title: '', body: '' }]);
 const [quiz, setQuiz] = useState(course?.quiz ?? [{ question: '', options: ['', ''], answer: 0 }]);
 function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); onSave({ ...course, id: course?.id ?? crypto.randomUUID(), title: text(f,'title'), description: text(f,'description'), category: text(f,'category') as Course['category'], delivery: text(f,'delivery') as Course['delivery'], tag: 'Demo authored course', skills: text(f,'skills').split(',').map(x => x.trim()).filter(Boolean), tools: text(f,'tools').split(',').map(x => x.trim()).filter(Boolean), outcome: text(f,'scope'), assignment: text(f,'assignment'), consultantId: text(f,'author'), status: 'review', lessons, quiz }, text(f,'access'), text(f,'reason'), text(f,'reviewer')); }
 return <form className="mp-card ma-course-editor" onSubmit={submit}>
  <label className="mp-field">Demo course author<select name="author" required defaultValue={course?.consultantId}>{roster.map(r => <option key={r.id} value={r.id}>{r.skill} · Approved demo trainer</option>)}</select></label>
  <label className="mp-field">Course title<input name="title" required maxLength={250} defaultValue={course?.title} /></label><label className="mp-field">Course description<textarea name="description" aria-label="Course description" required maxLength={5000} defaultValue={course?.description} /></label><label className="mp-field">Skill area<select name="category" defaultValue={course?.category}>{skillCategories.map(c => <option key={c.id} value={c.id}>{c.title}</option>)}</select></label><label className="mp-field">Delivery mode<select name="delivery" defaultValue={course?.delivery}><option value="self-paced">Self-paced text learning</option><option value="foundation">Foundation plan / role play</option></select></label><label className="mp-field">Skills (comma separated)<input name="skills" required maxLength={1000} defaultValue={course?.skills.join(', ')} /></label><label className="mp-field">Optional practice tools (comma separated)<input name="tools" maxLength={1000} defaultValue={course?.tools?.join(', ')} /></label><label className="mp-field">Learning scope and limits<textarea name="scope" aria-label="Learning scope and limits" required maxLength={5000} defaultValue={course?.outcome} /></label>
  <h4>Text-first lessons</h4>{lessons.map((l,i) => <fieldset className="ma-editor-item" key={i}><legend>Lesson {i + 1}</legend><label className="mp-field">Lesson {i + 1} title<input required maxLength={250} value={l.title} onChange={e => setLessons(lessons.map((x,j) => j === i ? {...x,title:e.target.value} : x))} /></label><label className="mp-field">Lesson {i + 1} text<textarea aria-label={`Lesson ${i + 1} text`} required maxLength={10000} value={l.body} rows={4} onChange={e => setLessons(lessons.map((x,j) => j === i ? {...x,body:e.target.value} : x))} /></label><button type="button" disabled={lessons.length === 1} onClick={() => setLessons(lessons.filter((_,j) => j !== i))}>Remove lesson {i + 1}</button></fieldset>)}<button type="button" disabled={lessons.length >= 20} onClick={() => setLessons([...lessons,{title:'',body:''}])}>Add text lesson</button>
  <h4>Quiz questions</h4>{quiz.map((q,i) => <fieldset key={i} className="ma-editor-item"><legend>Question {i + 1}</legend><label className="mp-field">Question {i + 1} text<input required maxLength={1000} value={q.question} onChange={e => setQuiz(quiz.map((x,j) => j === i ? {...x,question:e.target.value} : x))} /></label>{q.options.map((o,k) => <label className="mp-field" key={k}>Question {i + 1} option {k + 1}<input required maxLength={1000} value={o} onChange={e => setQuiz(quiz.map((x,j) => j === i ? {...x,options:x.options.map((v,n) => n === k ? e.target.value : v)} : x))} /></label>)}<label className="mp-field">Question {i + 1} correct option<select value={q.answer} onChange={e => setQuiz(quiz.map((x,j) => j === i ? {...x,answer:Number(e.target.value)} : x))}>{q.options.map((_,k) => <option key={k} value={k}>Option {k+1}</option>)}</select></label><button type="button" disabled={quiz.length === 1} onClick={() => setQuiz(quiz.filter((_,j) => j !== i))}>Remove question {i + 1}</button></fieldset>)}<button type="button" disabled={quiz.length >= 20} onClick={() => setQuiz([...quiz,{question:'',options:['',''],answer:0}])}>Add quiz question</button>
  <label className="mp-field">Practical assignment<textarea name="assignment" aria-label="Practical assignment" required maxLength={5000} rows={4} defaultValue={course?.assignment} /></label><label className="mp-field">Accessible delivery evidence<textarea name="access" aria-label="Accessible delivery evidence" required maxLength={5000} rows={3} /></label><p>Describe text alternatives, clear instructions, flexible pace and task-specific adaptations. This draft creates no workshop or observed-practice qualification.</p><label className="mp-field">Draft revision reason<textarea name="reason" required maxLength={5000} /></label><label className="mp-field">Draft reviewer label<input name="reviewer" required maxLength={250} defaultValue="Demo administrator" /></label><button className="primary">Save demo course draft</button>
 </form>;
}
