import test from 'node:test';
import assert from 'node:assert/strict';
import { freshSharedDemo, updateSharedDemo, saveSharedDemo, loadSharedDemo } from './sharedDemo';
import { syncLearner, submitTeaching, submitWork, addToPortfolio, USER_LEARNER_ID, USER_DEMO_KEY } from './userDemo';
import { decideReview, reviewRecord } from './reviewDemo';
import { enrol, enrolmentCourse, updateEnrolment } from './store';
import { assignLearning, currentAssignment, decideCourse, saveCourseDraft, courseCoordinationStatus, coursePublishIssues, type CourseDecisionInput, type LearningAssignmentInput } from './coordinationDemo';
import type { Course } from './catalogue';
function roster() {
  let s = freshSharedDemo();
  const d = submitTeaching(syncLearner({ ...s.user, profile: { ...s.user.profile, name: 'Learner' } }), { route: 'experience', skill: 'Foundation practice', examples: 'Work examples', explanation: 'Teaching steps', accessibility: 'Text and captions' }).demo;
  s = updateSharedDemo(s, d); const r = reviewRecord(s, 'teaching')!;
  return decideReview(s, { kind: 'teaching', submissionId: r.submission.id, expectedRevision: r.submission.revision, outcome: 'approved', reviewer: 'Administrator', reason: 'Four criteria reviewed', checklist: { skill: true, examples: true, explanation: true, accessibility: true } }).session;
}
function authored(): Course { return { id: 'authored', title: 'Foundation course', description: 'A local foundation demo', tag: 'Skills', skills: ['Foundation practice'], lessons: [{ title: 'Lesson', body: 'Text lesson' }], quiz: [{ question: 'Choose A', options: ['A', 'B'], answer: 0 }], assignment: 'Write a plan', status: 'review', consultantId: 'user-demo-trainer', delivery: 'foundation', category: 'digital', tools: ['Pen and paper'], outcome: 'Foundation written practice only; no specialist competence' }; }
function draft(s = roster(), c = authored()) { return saveCourseDraft(s, { course: c, expectedRevision: null, reason: 'New demo course', reviewer: 'Administrator', accessibilityEvidence: 'Text lesson and accessible quiz' }).session; }
function command(s: ReturnType<typeof freshSharedDemo>, courseId: string, outcome: CourseDecisionInput['outcome']): CourseDecisionInput { return { courseId, outcome, expectedRevision: s.recordMetadata[`course:${courseId}`].revision, reason: 'Demo coordination', reviewer: 'Administrator', ...(outcome === 'publish' ? { accessibilityEvidence: 'Text-first lessons and reviewed quiz' } : {}) }; }
function assignment(s: ReturnType<typeof freshSharedDemo>, kind: LearningAssignmentInput['kind'], recordId: string): LearningAssignmentInput { return { kind, recordId, expectedAssignmentId: currentAssignment(s, kind, recordId)?.assignment.id, expectedRevision: s.recordMetadata[`${kind}:${recordId}`].revision, rosterId: 'user-demo-trainer', suitabilityNote: 'Manually reviewed foundation mentoring scope; specialist observation is excluded', reason: 'Demo follow-up', reviewer: 'Administrator', ...(kind === 'enrolment' ? { submissionId: s.submissions.filter(x => x.kind === 'work' && x.recordId === recordId).at(-1)!.id } : {}) }; }
function storage(run: (data: Map<string, string>) => void) { const descriptor = Object.getOwnPropertyDescriptor(globalThis, 'sessionStorage'), data = new Map<string, string>([['mosaic-v1', 'separate sandbox']]); Object.defineProperty(globalThis, 'sessionStorage', { configurable: true, value: { getItem: (k: string) => data.get(k) ?? null, setItem: (k: string, v: string) => data.set(k, v), removeItem: (k: string) => data.delete(k) } }); try { run(data); } finally { if (descriptor) Object.defineProperty(globalThis, 'sessionStorage', descriptor); else Reflect.deleteProperty(globalThis, 'sessionStorage'); } }
test('publishing gates reject incomplete course, invalid quiz, video without transcript and unapproved author', () => {
  const s = roster(), c = authored();
  assert.deepEqual(coursePublishIssues(s, c, 'Reviewed access'), []);
  for (const patch of [{ assignment: '' }, { lessons: [] }, { quiz: [] }, { quiz: [{ question: 'Q', options: ['same', 'Same'], answer: 0 }] }, { lessons: [{ title: 'Video', body: 'Text', video: 'https://example.com/video' }] }, { consultantId: 'unapproved' }]) assert.ok(coursePublishIssues(s, { ...c, ...patch }, 'Reviewed access').length);
  assert.ok(coursePublishIssues(s, c).length); assert.ok(coursePublishIssues(s, { ...c, outcome: '' }, 'Reviewed access').length); assert.ok(coursePublishIssues(s, { ...c, tools: [] }, 'Reviewed access').length);
  const submitted = draft(s, { ...c, assignment: '' }); assert.ok(decideCourse(submitted, command(submitted, c.id, 'publish')).error);
  const unapproved = updateSharedDemo(freshSharedDemo(), { ...freshSharedDemo().user, learning: { ...freshSharedDemo().user.learning, courses: [...freshSharedDemo().user.learning.courses, c] } }); assert.ok(decideCourse(unapproved, command(unapproved, c.id, 'publish')).error);
});
test('draft creation and revisions require roster and preserve immutable decision evidence and stale gates', () => {
  const c = authored(), s = roster(); assert.ok(saveCourseDraft(freshSharedDemo(), { course: c, expectedRevision: null, reason: 'New', reviewer: 'Admin', accessibilityEvidence: 'Text' }).error);
  let d = draft(s); const firstDraft = structuredClone(d.coordination!.drafts![0]), cmd = command(d, c.id, 'needs-changes'); d = decideCourse(d, cmd).session; const firstDecision = structuredClone(d.coordination!.courseDecisions[0]);
  assert.equal(decideCourse(d, cmd).session, d); assert.ok(decideCourse(d, { ...cmd, reason: 'Different' }).error);
  const edit = { course: { ...c, assignment: 'Revised plan' }, expectedRevision: d.recordMetadata[`course:${c.id}`].revision, reason: 'Revised evidence', reviewer: 'Administrator', accessibilityEvidence: 'Text reviewed' }; const changed = saveCourseDraft(d, edit); assert.equal(changed.error, undefined); d = changed.session;
  assert.equal(saveCourseDraft(d, edit).session, d); assert.equal(courseCoordinationStatus(d, c.id), 'review'); assert.ok(decideCourse(d, { ...cmd, outcome: 'publish' }).error); assert.deepEqual(d.coordination!.drafts![0], firstDraft); assert.deepEqual(d.coordination!.courseDecisions[0], firstDecision);
  d = decideCourse(d, command(d, c.id, 'publish')).session; assert.equal(courseCoordinationStatus(d, c.id), 'published');
  assert.ok(saveCourseDraft(s, { ...edit, course: s.user.learning.courses[0], expectedRevision: 1 }).error);
});
test('seed archive and restore retain learner access and completion while blocking new enrolment', () => {
  let s = freshSharedDemo(), d = syncLearner({ ...s.user, profile: { ...s.user.profile, name: 'Learner' } }); const c = d.learning.courses[0]; d.learning = enrol(d.learning, USER_LEARNER_ID, c.id); delete d.learning.enrolments[0].courseVersion; s = updateSharedDemo(s, d);
  const id = s.user.learning.enrolments[0].id, archive = command(s, c.id, 'archive'); s = decideCourse(s, archive).session;
  assert.equal(courseCoordinationStatus(s, c.id), 'archived'); assert.deepEqual(enrolmentCourse(s.user.learning, s.user.learning.enrolments[0]), c); assert.equal(enrol({ ...s.user.learning, enrolments: [] }, USER_LEARNER_ID, c.id).enrolments.length, 0);
  d = submitWork(s.user, id, 'Practical plan'); d.learning = updateEnrolment(d.learning, id, { lessons: c.lessons.map((_, i) => i), scores: [70], approved: true }); assert.ok(d.learning.enrolments[0].completedAt); d = addToPortfolio(d, id); assert.equal(d.portfolio[0].title, c.title);
  s = updateSharedDemo(s, d, { kind: 'work-submitted', recordId: id }); const restored = decideCourse(s, command(s, c.id, 'publish')); assert.equal(restored.error, undefined); assert.equal(courseCoordinationStatus(restored.session, c.id), 'published'); assert.deepEqual(restored.session.user.learning.enrolments, s.user.learning.enrolments);
});
test('authored revision retains enrolled content and demonstrated skills across publish', () => {
  let s = draft(); s = decideCourse(s, command(s, 'authored', 'publish')).session; let d = s.user; d.learning = enrol(d.learning, USER_LEARNER_ID, 'authored'); s = updateSharedDemo(s, d); const old = structuredClone(s.user.learning.enrolments[0].courseVersion);
  const edit = saveCourseDraft(s, { course: { ...authored(), lessons: [{ title: 'New', body: 'New body' }, { title: 'Extra', body: 'Extra body' }], skills: ['New skills'] }, expectedRevision: s.recordMetadata['course:authored'].revision, reason: 'Revise', reviewer: 'Admin', accessibilityEvidence: 'Text reviewed' }); assert.equal(edit.error, undefined); s = edit.session; assert.deepEqual(s.user.learning.enrolments[0].courseVersion, old);
  const id = s.user.learning.enrolments[0].id; d = submitWork(s.user, id, 'Old plan'); d.learning = updateEnrolment(d.learning, id, { lessons: [0], scores: [100], approved: true }); d = syncLearner(d); assert.ok(d.learning.enrolments[0].completedAt); assert.ok(d.learning.learners[0].skills.includes('Foundation practice')); assert.ok(!d.learning.learners[0].skills.includes('New skills'));
});
test('assignments require explicit roster suitability, reject stale records and never assess practical work or reply', () => {
  let s = roster(); const c = s.user.learning.courses[0]; let d = s.user; d.learning = enrol(d.learning, USER_LEARNER_ID, c.id); d.learning.requests.push({ id: 'question', learnerId: USER_LEARNER_ID, courseId: c.id, kind: 'question', text: 'How?', createdAt: Date.now() }); s = updateSharedDemo(s, d); const id = s.user.learning.enrolments[0].id; s = updateSharedDemo(s, submitWork(s.user, id, 'Evidence'), { kind: 'work-submitted', recordId: id });
  for (const [kind, recordId] of [['course', c.id], ['enrolment', id], ['question', 'question']] as const) { const cmd = assignment(s, kind, recordId); assert.ok(assignLearning(s, { ...cmd, suitabilityNote: '' }).error); assert.ok(assignLearning(s, { ...cmd, rosterId: 'unknown' }).error); assert.ok(assignLearning(s, { ...cmd, expectedRevision: 999 }).error); const before = structuredClone(s.user), count = s.events.length; const result = assignLearning(s, cmd); assert.equal(result.error, undefined); s = result.session; assert.equal(assignLearning(s, cmd).session, s); assert.equal(s.events.length, count + 1); assert.deepEqual(s.user, before); assert.equal(currentAssignment(s, kind, recordId)?.stale, false); }
  const old = assignment(s, 'enrolment', id), history = structuredClone(s.coordination!.assignments); s = updateSharedDemo(s, submitWork(s.user, id, 'Evidence'), { kind: 'work-submitted', recordId: id }); assert.equal(currentAssignment(s, 'enrolment', id)?.stale, true); assert.equal(assignLearning(s, old).session, s); assert.ok(assignLearning(s, { ...old, reason: 'New stale request' }).error); assert.equal(s.user.learning.enrolments[0].approved, false); s = assignLearning(s, assignment(s, 'enrolment', id)).session; assert.deepEqual(s.coordination!.assignments.slice(0, history.length), history); assert.equal(currentAssignment(s, 'enrolment', id)?.stale, false);
  d = structuredClone(s.user); d.learning.requests[0].text = 'Revised question'; s = updateSharedDemo(s, d); assert.equal(currentAssignment(s, 'question', 'question')?.stale, true); storage(() => { assert.equal(saveSharedDemo(s), true); assert.deepEqual(loadSharedDemo().session, JSON.parse(JSON.stringify(s))); });
});
test('coordination saves and reloads, older schema normalizes, malformed state preserves stored bytes', () => storage(data => {
  let s = draft(); s = decideCourse(s, command(s, 'authored', 'publish')).session; s = assignLearning(s, assignment(s, 'course', 'authored')).session; assert.equal(saveSharedDemo(s), true); assert.deepEqual(loadSharedDemo().session, JSON.parse(JSON.stringify(s))); assert.equal(data.get('mosaic-v1'), 'separate sandbox');
  for (const corrupt of [(d: typeof s) => { d.user.learning.courses.find(c => c.id === 'authored')!.status = 'review'; }, (d: typeof s) => { d.coordination!.courseDecisions[0].courseVersion.assignment = ''; }, (d: typeof s) => { d.coordination!.assignments[0].rosterId = 'unknown'; }, (d: typeof s) => { d.coordination!.drafts![0].course.lessons = null as unknown as Course['lessons']; }, (d: typeof s) => { d.coordination!.assignments.push(d.coordination!.assignments[0]); }]) { const invalid = structuredClone(s); corrupt(invalid); const raw = JSON.stringify(invalid); data.set(USER_DEMO_KEY, raw); assert.ok(loadSharedDemo().recovery); assert.equal(saveSharedDemo(s), false); assert.equal(data.get(USER_DEMO_KEY), raw); }
  const old = freshSharedDemo(); delete old.coordination; data.set(USER_DEMO_KEY, JSON.stringify(old)); assert.deepEqual(loadSharedDemo().session.coordination, { courseDecisions: [], assignments: [] });
}));
test('malformed retained versions preserve storage and retained enrolment content cannot be overwritten', () => storage(data => {
  let s = roster(), d = s.user; const c = d.learning.courses[0]; d.learning = enrol(d.learning, USER_LEARNER_ID, c.id); s = updateSharedDemo(s, d); const original = structuredClone(s.user.learning.enrolments[0].courseVersion); d = structuredClone(s.user); d.learning.enrolments[0].courseVersion!.skills = ['forged']; assert.deepEqual(updateSharedDemo(s, d).user.learning.enrolments[0].courseVersion, original);
  for (const bad of [null, { ...c, id: 'wrong' }, { ...c, quiz: [{ question: 'Bad', options: ['A'], answer: 9 }] }]) { const invalid = structuredClone(s); invalid.user.learning.enrolments[0].courseVersion = bad as unknown as Course; const raw = JSON.stringify(invalid); data.set(USER_DEMO_KEY, raw); assert.ok(loadSharedDemo().recovery); assert.equal(data.get(USER_DEMO_KEY), raw); }
}));
test('assignment concurrency keeps A to B history stable when A is replayed and rejects stale replacements', () => storage(data => {
  let s = roster(); const courseId = s.user.learning.courses[0].id;
  const first = assignment(s, 'course', courseId), revision = first.expectedRevision;
  s = assignLearning(s, first).session; const a = currentAssignment(s, 'course', courseId)!.assignment;
  const second = { ...assignment(s, 'course', courseId), suitabilityNote: 'Revised foundation mentoring suitability', reason: 'Replace the first coordination choice' };
  const result = assignLearning(s, second); assert.equal(result.error, undefined); s = result.session; const b = currentAssignment(s, 'course', courseId)!.assignment;
  assert.notEqual(a.id, b.id); assert.equal(b.expectedAssignmentId, a.id); assert.equal(s.recordMetadata[`course:${courseId}`].revision, revision);
  const before = structuredClone(s); assert.equal(assignLearning(s, first).session, s); assert.deepEqual(s, before); assert.equal(currentAssignment(s, 'course', courseId)!.assignment.id, b.id);
  for (const stale of [{ ...second, reason: 'Another replacement from old screen' }, { ...first, reason: 'Missing current assignment guard' }]) { const rejected = assignLearning(s, stale); assert.ok(rejected.error); assert.equal(rejected.session, s); }
  const third = { ...assignment(s, 'course', courseId), reason: 'Fresh replacement after checking B' }; const replaced = assignLearning(s, third); assert.equal(replaced.error, undefined); s = replaced.session; assert.equal(s.coordination!.assignments.length, 3); assert.equal(currentAssignment(s, 'course', courseId)!.assignment.expectedAssignmentId, b.id); assert.equal(s.recordMetadata[`course:${courseId}`].revision, revision);
  assert.equal(saveSharedDemo(s), true); assert.deepEqual(loadSharedDemo().session, JSON.parse(JSON.stringify(s)));
  for (const id of [undefined, a.id, 'unrelated-record']) { const invalid = structuredClone(s); invalid.coordination!.assignments[2].expectedAssignmentId = id; const raw = JSON.stringify(invalid); data.set(USER_DEMO_KEY, raw); assert.ok(loadSharedDemo().recovery); assert.equal(data.get(USER_DEMO_KEY), raw); }
}));
