import test from 'node:test';
import assert from 'node:assert/strict';
import { freshSharedDemo,updateSharedDemo } from './sharedDemo';
import { syncLearner,submitSupport,USER_LEARNER_ID } from './userDemo';
import { loadSampleCohort } from './reportingDemo';
import { enrol,updateEnrolment } from './store';
import { aggregateGrantCsv,csvCell,detailedGrantCsv,grantPlanning,SAMPLE_NOT_COLLECTED } from './grantPlanning';
function fixture(){const s=freshSharedDemo();return updateSharedDemo(s,syncLearner({...s.user,profile:{...s.user.profile,name:'PRIVATE_NAME_SENTINEL',contact:'PRIVATE_CONTACT_SENTINEL',state:'Plateau',lga:'Jos North'}}));}
const user={scope:'user' as const,state:''};
test('grant breakdowns deduplicate multi-select answers and distinguish missing and explicit declined disclosures',()=>{
 const s=fixture();s.user.profile.disabilities=['Visual','Visual','Hearing'];s.user.profile.gender='Prefer not to say';s.user.profile.skills=['Teaching','Teaching'];let r=grantPlanning(s,user);assert.equal(r.breakdowns.find(b=>b.dimension==='Disability disclosure'&&b.category==='Visual')?.count,1);assert.equal(r.breakdowns.find(b=>b.category==='Prefer not to say')?.count,1);assert.equal(r.breakdowns.find(b=>b.dimension==='Self-reported skills (unverified)'&&b.category==='Teaching')?.count,1);assert.ok(r.breakdowns.every(b=>b.denominator===1));
 s.user.profile.gender='';s.user.profile.disabilities=[];r=grantPlanning(s,user);assert.equal(r.breakdowns.filter(b=>b.category==='Not disclosed').length,2);s.user.profile.disabilityDescription='PRIVATE_DISABILITY_DESCRIPTION';assert.ok(grantPlanning(s,user).breakdowns.some(b=>b.category==='Self-description recorded'));
});
test('grant cohort scope and state exclude User evidence and never infer sample demographics',()=>{
 const s=loadSampleCohort(fixture());const samples=grantPlanning(s,{scope:'samples',state:''});assert.equal(samples.rows.length,5);assert.equal(samples.enrolled,0);assert.ok(samples.breakdowns.filter(b=>b.dimension==='Gender disclosure'||b.dimension==='Self-reported skills (unverified)').every(b=>b.category===SAMPLE_NOT_COLLECTED&&b.count===5));const plateau=grantPlanning(s,{scope:'all',state:'Plateau'});assert.equal(plateau.rows.length,3);assert.equal(plateau.userCount,1);assert.equal(grantPlanning(s,{scope:'all',state:'Lagos'}).userCount,0);assert.equal(grantPlanning(s,{scope:'user',state:'Lagos'}).rows.length,0);
 assert.equal(grantPlanning(freshSharedDemo()).rows.length,0);
});
test('completed grant skills retain enrolled course evidence independently of interests and current catalogue',()=>{
 const s=fixture(),d=s.user;d.profile.skills=['Teaching'];const interest=d.learning.courses[1].title;d.profile.interests=[interest];d.learning=enrol(d.learning,USER_LEARNER_ID,'digital-essentials');const e=d.learning.enrolments[0],course=e.courseVersion!;const expected=[...new Set(course.skills)];d.learning=updateEnrolment(d.learning,e.id,{lessons:course.lessons.map((_,i)=>i),scores:[100],submitted:'PRIVATE_WORK_SENTINEL',approved:true});d.learning.courses=d.learning.courses.map(c=>c.id===course.id?{...c,skills:['New replacement skill']}:c);const r=grantPlanning(s,user);assert.deepEqual(r.completedSkills,expected);assert.equal(r.completed,1);assert.equal(r.enrolled,1);assert.ok(!r.completedSkills.includes('Teaching'));assert.ok(!r.completedSkills.includes('New replacement skill'));assert.ok(r.breakdowns.some(b=>b.dimension==='Course interests'&&b.category===interest));
});
test('aggregate CSV excludes direct identifiers and authored descriptions, sanitizes unconstrained responses, records scope and state',()=>{
 let s=fixture();const sentinel='PRIVATE_TEXT_SENTINEL';Object.assign(s.user.profile,{genderDescription:sentinel,disabilityDescription:sentinel,experience:sentinel,certificates:sentinel,portfolioDescription:sentinel,otherSupport:sentinel,device:sentinel,internet:sentinel,language:sentinel,availability:sentinel,gender:sentinel,disabilities:[sentinel],access:[sentinel],skills:[sentinel],goals:[sentinel],categories:[sentinel]});s=updateSharedDemo(s,submitSupport({...s.user,support:[{id:sentinel,need:sentinel,available:sentinel,priority:sentinel}]}));const text=aggregateGrantCsv(s,user);for(const privateText of [sentinel,'PRIVATE_NAME_SENTINEL','PRIVATE_CONTACT_SENTINEL'])assert.equal(text.includes(privateText),false);assert.ok(text.includes('Other recorded response'));assert.ok(text.includes('Self-description recorded'));assert.ok(text.includes('"user","All states"'));const filtered=aggregateGrantCsv(s,{scope:'samples',state:'Lagos'});assert.ok(filtered.includes('"samples","Lagos"'));
});
test('detailed CSV requires its own consent, includes whitelisted profile/support fields and excludes history/practical metadata',()=>{
 let s=fixture();s.user.profile.genderDescription='Detailed gender';s.user.profile.portfolioDescription='Unverified portfolio';s=updateSharedDemo(s,submitSupport({...s.user,support:[{id:'SECRET_ITEM_ID',need:'Need, with comma\nand "quote"',available:'Own phone',priority:'High'}]}));s.events.push({id:'history',kind:'test',recordId:'test',at:1,actor:'user',description:'SECRET_HISTORY'});s.user.attachments.push({id:'attachment',name:'SECRET_ATTACHMENT',description:'SECRET_FILE_DESCRIPTION',type:'application/pdf',size:1});assert.throws(()=>detailedGrantCsv(s,user,false),/consent/);const text=detailedGrantCsv(s,user,true);for(const visible of ['PRIVATE_NAME_SENTINEL','PRIVATE_CONTACT_SENTINEL','Detailed gender','Unverified portfolio','Own phone'])assert.ok(text.includes(visible));for(const hidden of ['SECRET_HISTORY','SECRET_ATTACHMENT','SECRET_FILE_DESCRIPTION','SECRET_ITEM_ID'])assert.equal(text.includes(hidden),false);const sample=detailedGrantCsv(loadSampleCohort(s),{scope:'samples',state:''},true);assert.ok(sample.includes(SAMPLE_NOT_COLLECTED));assert.equal(sample.includes('PRIVATE_NAME_SENTINEL'),false);
});
test('CSV quoting preserves commas multiline and doublequotes and neutralizes spreadsheet formula prefixes',()=>{
 assert.equal(csvCell('a,b\n"c"'),'"a,b\n""c"""');for(const input of ['=1+1',' +SUM(1)','-1','@cmd','\t=cmd','\n=cmd'])assert.ok(csvCell(input).startsWith('"\''));assert.equal(csvCell('ordinary'),'"ordinary"');
});

test('aggregate labels never expose arbitrary geography, interests or retained authored course narratives',()=>{
 const s=fixture(),secret='PRIVATE_NARRATIVE_SENTINEL';s.user.profile.state=secret;s.user.profile.lga=secret;s.user.profile.interests=[secret];s.user.learning=enrol(s.user.learning,USER_LEARNER_ID,'digital-essentials');const e=s.user.learning.enrolments[0];e.courseVersion={...e.courseVersion!,title:secret,skills:[secret]};e.completedAt=1;const r=grantPlanning(s,user);assert.ok(r.completedSkills.includes(secret),'raw retained detail remains available only for consented detail');assert.equal(JSON.stringify(r.breakdowns).includes(secret),false);assert.equal(aggregateGrantCsv(s,user).includes(secret),false);const filtered=aggregateGrantCsv(s,{scope:'user',state:secret});assert.equal(filtered.includes(secret),false);assert.ok(filtered.includes('Other recorded location'));
});
