import type { GrantPlanning, GrantBreakdown } from './grantPlanning';
import { SAMPLE_NOT_COLLECTED } from './grantPlanning';
import { validNigeriaAtlas } from './geographyDemo';
/** All labels are canonical aggregate categories; raster pages preserve Unicode. */
export async function grantPlanningPdf(report: GrantPlanning): Promise<Blob> {
 const response=await fetch('/nigeria-admin-map.json');
 if(!response.ok)throw new Error('The local Nigeria map could not be loaded.');
 const atlas:unknown=await response.json();if(!validNigeriaAtlas(atlas))throw new Error('The local Nigeria map failed validation.');
 const width=1240,height=1754,left=72,right=1168,gap=28,col=(right-left-gap)/2;
 const ink='#183d37',blue='#255775',green='#167569',gold='#b55a38',muted='#536663',gray='#a9b7b2',paper='#f4f7f4';
 const pages:HTMLCanvasElement[]=[];let canvas=document.createElement('canvas'),ctx=canvas.getContext('2d')!,y=0;
 const generated=new Date().toISOString(),scope=report.filters.scope,stateFilter=report.filters.state||'All states and FCT',count=report.rows.length;
 const items=(d:string)=>report.breakdowns.filter(b=>b.dimension===d);
 const userItems=(d:string)=>items(d).filter(b=>b.category!==SAMPLE_NOT_COLLECTED);
 const percent=(n:number,d:number)=>d?`${(n/d*100).toFixed(1)}%`:'—';
 const coverage=(d:string)=>report.userCount-(items(d).find(b=>b.category==='Not disclosed')?.count||0);
 function wrap(value:string,max:number,font='24px Arial'){ctx.font=font;const out:string[]=[];let line='';for(const word of value.split(/\s+/)){if(ctx.measureText(line+(line?' ':'')+word).width<=max){line+=(line?' ':'')+word;continue;}if(line){out.push(line);line='';}for(const ch of Array.from(word)){if(ctx.measureText(line+ch).width>max&&line){out.push(line);line='';}line+=ch;}}if(line)out.push(line);return out.length?out:[''];}
 function text(value:string,x:number,top:number,max:number,size=24,bold=false,color=ink){const font=`${bold?'bold ':''}${size}px Arial`;const lines=wrap(value,max,font);ctx.font=font;ctx.fillStyle=color;lines.forEach((v,i)=>ctx.fillText(v,x,top+i*(size+8)));return lines.length*(size+8);}
 function fill(x:number,top:number,w:number,h:number,color=paper){ctx.fillStyle=color;ctx.fillRect(x,top,w,h);}
 function rule(top:number){ctx.strokeStyle='#cbd7d0';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(left,top);ctx.lineTo(right,top);ctx.stroke();}
 function page(section:string,title:string,subtitle:string){canvas=document.createElement('canvas');canvas.width=width;canvas.height=height;ctx=canvas.getContext('2d')!;if(!ctx)throw new Error('PDF rendering unavailable');fill(0,0,width,height,'#fff');fill(0,0,width,18,ink);text('MOSAIC PATHWAYS  /  GRANT PLANNING',left,72,1000,20,true,blue);text(section.toUpperCase(),left,120,1000,18,true,green);text(title,left,180,1096,43,true);const used=text(subtitle,left,226,1096,23,false,muted);y=226+used+28;rule(y);y+=30;pages.push(canvas);}
 function table(x:number,top:number,w:number,headers:string[],rows:string[][],ratios:number[],title?:string){let at=top;if(title){at+=text(title,x,at,w,26,true)+20;}const widths=ratios.map(r=>r*w),draw=(values:string[],header=false)=>{const font=`${header?'bold ':''}21px Arial`,wrapped=values.map((v,i)=>wrap(v,widths[i]-24,font));const h=Math.max(...wrapped.map(v=>v.length))*28+24;fill(x,at-19,w,h,header?'#dfeae4':paper);let px=x;ctx.font=font;ctx.fillStyle=ink;wrapped.forEach((ls,i)=>{ls.forEach((v,j)=>ctx.fillText(v,px+12,at+j*28));px+=widths[i];});at+=h;};draw(headers,true);rows.forEach(r=>draw(r));return at+8;}
 function note(x:number,top:number,w:number,value:string){fill(x,top,w,100,'#eaf1ed');text(value,x+18,top+32,w-36,22,false,muted);}
 function kpi(x:number,top:number,w:number,label:string,value:number,detail:string){fill(x,top,w,174);text(label,x+20,top+34,w-40,21,true);text(String(value),x+20,top+109,w-40,52,true,blue);text(detail,x+20,top+150,w-40,18,false,muted);}
 function bars(x:number,top:number,w:number,title:string,dimension:string,subset:GrantBreakdown[]){const rows=subset.map(b=>({b,lines:wrap(`${b.category} · ${b.count} / ${report.userCount}`,w-44,'23px Arial')}));const h=110+(rows.length?rows.reduce((n,r)=>n+r.lines.length*31+32,0):96);fill(x,top,w,h);let at=top+37;at+=text(title,x+20,at,w-40,25,true)+12;text(`Selected User profiles · n = ${report.userCount}`,x+20,at,w-40,19,false,muted);at+=38;if(!rows.length){text('No User profile selected. No disclosure or learning evidence is inferred.',x+20,at,w-40,23,false,muted);}for(const {b,lines} of rows){const missing=['Not recorded','Not disclosed','Not confirmed','Prefer not to say'].includes(b.category);ctx.font='23px Arial';ctx.fillStyle=ink;lines.forEach(v=>{ctx.fillText(v,x+20,at);at+=31;});fill(x+20,at-10,w-40,12,'#dce6df');fill(x+20,at-10,(w-40)*(report.userCount?b.count/report.userCount:0),12,missing?gray:blue);at+=32;}return h;}
 function flow(top:number){text('Recorded learning pathway',left,top,1000,27,true);const w=480,at=top+32;fill(left,at,w,142,'#e5f0eb');fill(right-w,at,w,142,'#e6edf3');text('COURSE ENROLMENTS',left+20,at+33,w-40,19,true,green);text(String(report.enrolled),left+20,at+101,w-40,48,true);text('COMPLETED ENROLMENTS',right-w+20,at+33,w-40,19,true,blue);text(`${report.completed}  (${percent(report.completed,report.enrolled)})`,right-w+20,at+101,w-40,42,true);ctx.strokeStyle=blue;ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(left+w+8,at+72);ctx.lineTo(right-w-8,at+72);ctx.stroke();ctx.beginPath();ctx.moveTo(right-w-22,at+60);ctx.lineTo(right-w-8,at+72);ctx.lineTo(right-w-22,at+84);ctx.stroke();text('A recorded sequence, not a measure of employment or programme impact.',left,at+184,1096,23,false,muted);return at+225;}
 // 01 — Executive briefing
 page('01 / Executive briefing','A recorded foundation for grant planning',`Nigeria · Scope: ${scope} · State/FCT filter: ${stateFilter}`);
 const kpis=[['Selected profiles',count,'Current filtered cohort'],['User-created profiles',report.userCount,'Optional profile responses'],['Geographic samples',report.sampleCount,'Fictional; geography only'],['Submitted support items',report.supportItems.length,'Latest submitted checklist']] as const;
 kpis.forEach(([label,value,detail],i)=>kpi(left+i*280,y,256,label,value,detail));y+=214;
 y=table(left,y,1096,['Planning measure','Recorded','How to read it'],[
 ['Completed course enrolments',`${report.completed} / ${report.enrolled}`,'Retained course evidence; not observed trade competence'],
 ['Gender answers recorded',`${coverage('Gender disclosure')} / ${report.userCount}`,'User profiles only; includes explicit prefer not to say'],
 ['Disability disclosures recorded',`${coverage('Disability disclosure')} / ${report.userCount}`,'At least one selected category or self-description'],
 ['Support items submitted',String(report.supportItems.length),'Requested needs; does not mean support delivered'],
 ],[.37,.17,.46],'Evidence at a glance');y+=35;y=flow(y);
 text('Use this report as a planning brief',left,y,1096,28,true);y+=45;
 const instructions=[['Target assistance', 'Use disclosed access preferences and submitted need counts to frame questions for applicants. Individual need narratives are deliberately omitted.'],['Describe the evidence', 'Keep unverified existing skills separate from completed course skills, interests and enrolments. Do not claim population prevalence or impact.'],['Protect disclosures', 'Small groups may identify a person. Aggregate categories are shared voluntarily; names, contact and descriptions are excluded.']];
 instructions.forEach(([label,body],i)=>{const top=y+i*125;text(`0${i+1}`,left,top,70,28,true,green);text(label,left+78,top,1018,24,true);text(body,left+78,top+38,1018,23,false,muted);});
 // 02 — Nigeria geography, actual pinned state geometry
 const stateRows=items('State'),knownStates=stateRows.filter(b=>atlas.states.some(s=>s.name===b.category)),lgaRows=items('LGA');
 page('02 / Geographic footprint','Where selected profiles are recorded',`Nigeria · ${knownStates.length} of 37 states/FCT represented · ${count} selected profiles · Filter: ${stateFilter}`);
 const mapTop=y,mapW=700,mapH=625;fill(left,mapTop,mapW,mapH);const scale=Math.min((mapW-40)/atlas.width,(mapH-90)/atlas.height),mapX=left+20+(mapW-40-atlas.width*scale)/2,mapY=mapTop+20;
 ctx.save();ctx.translate(mapX,mapY);ctx.scale(scale,scale);atlas.states.forEach(s=>{const n=knownStates.find(b=>b.category===s.name)?.count||0;ctx.fillStyle=n? n>=3?'#173f36':n===2?'#3c7965':'#81ac98':'#dce3df';ctx.strokeStyle='#fff';ctx.lineWidth=1.7/scale;const path=new Path2D(s.path);ctx.fill(path);ctx.stroke(path);});ctx.restore();
 const placed:{x:number;y:number;w:number}[]=[];
 knownStates.forEach(b=>{const area=atlas.states.find(s=>s.name===b.category)!;const x=mapX+area.center[0]*scale,z=mapY+area.center[1]*scale;ctx.beginPath();ctx.arc(x,z,13,0,Math.PI*2);ctx.fillStyle=blue;ctx.fill();ctx.strokeStyle='#fff';ctx.lineWidth=2;ctx.stroke();ctx.fillStyle='#fff';ctx.font='bold 18px Arial';ctx.textAlign='center';ctx.fillText(String(b.count),x,z+6);ctx.textAlign='left';ctx.font='bold 19px Arial';const labelWidth=ctx.measureText(b.category).width;let labelX=Math.max(left+20,Math.min(left+mapW-labelWidth-20,x+(b.category==='FCT'?-labelWidth-32:22))),labelY=z+(b.category==='Lagos'?28:b.category==='FCT'?-33:-20);while(placed.some(p=>Math.abs(p.y-labelY)<25&&labelX<p.x+p.w+10&&labelX+labelWidth>p.x-10))labelY+=28;placed.push({x:labelX,y:labelY,w:labelWidth});ctx.strokeStyle=blue;ctx.lineWidth=1.4;ctx.beginPath();ctx.moveTo(x,z);ctx.lineTo(labelX+(labelX<x?labelWidth:0),labelY-7);ctx.stroke();fill(labelX-4,labelY-20,labelWidth+8,25,'#ffffff');text(b.category,labelX,labelY,labelWidth+2,19,true,blue);});
 text('NIGERIA',left+20,mapTop+mapH-28,mapW-40,20,true,blue);
 const sideX=left+mapW+gap,sideW=right-sideX;
 let sideY=table(sideX,mapTop+25,sideW,['State / FCT','Count','Share'],stateRows.map(b=>[b.category,String(b.count),percent(b.count,count)]),[.50,.25,.25],'Recorded state distribution');
 text('Shares use all selected profiles. Gray states have no selected records; this is not zero population or unmet-need evidence.',sideX,sideY+20,sideW,22,false,muted);
 y=mapTop+mapH+30;const legend=[['#81ac98','1 selected profile'],['#3c7965','2 selected profiles'],['#173f36','3+ selected profiles'],['#dce3df','No selected profiles recorded']];legend.forEach(([color,label],i)=>{const x=left+(i%2)*550,z=y+Math.floor(i/2)*42;fill(x,z,20,20,color);text(label,x+32,z+18,510,21,false,muted);});y+=112;
 text(`Selected LGAs: ${lgaRows.filter(b=>!['Not recorded','Other recorded location'].includes(b.category)).length} · Location counts do not measure geographic coverage.`,left,y,1096,24,true);y+=45;
 y=table(left,y,1096,['Recorded LGA category','Profiles','Share of selected cohort'],lgaRows.map(b=>[b.category,String(b.count),percent(b.count,count)]),[.56,.16,.28]);
 text('Pinned local boundary source: GRID3 Nigeria represented 2022 via geoBoundaries, CC BY 4.0. State polygons are drawn from the same atlas as the learner map.',left,Math.max(y+28,1490),1096,20,false,muted);
 // 03 — Disclosure and circumstances. Sample missingness is a separate callout.
 page('03 / Voluntary disclosures','People, preferences and learning access',`Profile charts use selected User profiles only (n = ${report.userCount}). ${report.sampleCount} geographic samples have no demographic or access data.`);
 const gender=userItems('Gender disclosure'),pieTop=y;fill(left,pieTop,col,450);text('Gender disclosure',left+20,pieTop+37,col-40,27,true);text(`User denominator: ${report.userCount}`,left+20,pieTop+76,col-40,20,false,muted);
 const cx=left+col/2,cy=pieTop+215,radius=105;let angle=-Math.PI/2;const palette=[blue,green,gold,'#8a6c16','#79558c'];
 if(!gender.length){ctx.beginPath();ctx.arc(cx,cy,radius,0,Math.PI*2);ctx.fillStyle='#dce3df';ctx.fill();}
 gender.forEach((b,i)=>{const next=angle+2*Math.PI*(report.userCount?b.count/report.userCount:0);ctx.beginPath();ctx.moveTo(cx,cy);ctx.arc(cx,cy,radius,angle,next);ctx.closePath();ctx.fillStyle=['Not disclosed','Prefer not to say'].includes(b.category)?gray:palette[i%palette.length];ctx.fill();angle=next;});
 let legendY=pieTop+354;gender.forEach((b,i)=>{fill(left+22,legendY-16,15,15,['Not disclosed','Prefer not to say'].includes(b.category)?gray:palette[i%palette.length]);legendY+=text(`${b.category}: ${b.count} / ${report.userCount} (${percent(b.count,report.userCount)})`,left+48,legendY,col-68,21)+7;});if(!gender.length)text('No User profile selected; gender is not collected for samples.',left+22,legendY,col-44,22,false,muted);
 const disabilityH=bars(left+col+gap,pieTop,col,'Disability disclosures','Disability disclosure',userItems('Disability disclosure'));
 y=pieTop+Math.max(450,disabilityH)+35;
 const accessH=bars(left,y,col,'Access preferences','Access preferences',userItems('Access preferences'));
 const circumstances=['Device','Internet','Language','Availability'].flatMap(d=>userItems(d).map(b=>[d,b.category,`${b.count} / ${report.userCount}`]));const circumstanceEnd=table(left+col+gap,y+24,col,['Circumstance','Recorded category','Profiles'],circumstances,[.29,.51,.2],'Learning circumstances');
 y=Math.max(y+accessH,circumstanceEnd)+38;
 const missing=(d:string)=>items(d).find(b=>b.category==='Not disclosed')?.count||0,declined=items('Gender disclosure').find(b=>b.category==='Prefer not to say')?.count||0;
 y=table(left,y,1096,['Optional field','User disclosed','Not disclosed','Prefer not to say','Samples not collected'],[
 ['Gender',`${report.userCount-missing('Gender disclosure')-declined} / ${report.userCount}`,`${missing('Gender disclosure')} / ${report.userCount}`,`${declined} / ${report.userCount}`,`${report.sampleCount} / ${count}`],
 ['Disability',`${report.userCount-missing('Disability disclosure')} / ${report.userCount}`,`${missing('Disability disclosure')} / ${report.userCount}`,'No separate option',`${report.sampleCount} / ${count}`],
 ],[.19,.2,.19,.2,.22],'Disclosure coverage and missing information');y+=22;
 text('Prefer not to say records an explicit choice not to disclose. Disability and access are voluntary, independent and multi-select. Counts can exceed the User denominator. Self-descriptions are reported only as “Self-description recorded”.',left,y,1096,23,false,muted);
 // 04 — Skills and support with continuation panels if many retained skills.
 page('04 / Skills and support','Distinguish ability, learning and requests',`Charts count each selected User profile once per category (n = ${report.userCount}). ${report.sampleCount} geographic samples have no skills or support evidence.`);
 const dimensions=[['Self-reported skills (unverified)','Existing skills · unverified'],['Completed course skills (retained evidence)','Completed course skills'],['Access preferences','Access preferences'],['Submitted support priorities','Submitted support priorities']];
 let gridY=y,slot=0,rowHeight=0;const charted=new Set<string>(['Gender disclosure','Disability disclosure','Access preferences','Device','Internet','Language','Availability','State','LGA']);
 for(const [dimension,title] of dimensions){charted.add(dimension);const all=userItems(dimension),chunks=all.length?Array.from({length:Math.ceil(all.length/8)},(_,i)=>all.slice(i*8,i*8+8)):[[]];for(let i=0;i<chunks.length;i++){const estimated=110+(chunks[i].length?chunks[i].reduce((n,b)=>n+wrap(`${b.category} · ${b.count} / ${report.userCount}`,col-44,'23px Arial').length*31+32,0):96);if(gridY+estimated>1460){page('04 / Skills and support · continued','Recorded skills and support categories',`Selected User profiles n = ${report.userCount}; samples excluded from these category denominators.`);gridY=y;slot=0;rowHeight=0;}const h=bars(left+slot*(col+gap),gridY,col,title+(i?' · continued':''),dimension,chunks[i]);rowHeight=Math.max(rowHeight,h);if(slot===0)slot=1;else{gridY+=rowHeight+30;slot=0;rowHeight=0;}}}
 y=gridY+(slot?rowHeight:0)+40;if(y+270>1540){page('04 / Recorded learning','What course records show','Learning counts describe retained course evidence, not employment or income.');}flow(y);
 // Appendix includes every remaining aggregate dimension, with contextual table headings.
 const remaining=[...new Set(report.breakdowns.map(b=>b.dimension))].filter(d=>!charted.has(d));
 if(remaining.length){page('05 / Additional planning categories','Additional planning categories',`All selected profiles n = ${count}. Geographic samples are explicitly marked “Not collected for geographic sample”.`);let top=y,colSlot=0,band=0;for(const d of remaining){const rows=items(d).map(b=>[b.category,String(b.count),String(b.denominator)]),estimated=85+rows.reduce((n,r)=>n+Math.max(...r.map((v,i)=>wrap(v,col*[.64,.16,.2][i]-24,'21px Arial').length))*28+24,0);if(top+estimated>1500){page('05 / Additional planning categories · continued','Additional planning categories',`Counts are profiles per category; denominator is ${count} selected profiles.`);top=y;colSlot=0;band=0;}const end=table(left+colSlot*(col+gap),top,col,['Category','Count','Cohort n'],rows,[.64,.16,.2],d);band=Math.max(band,end-top);if(colSlot===0)colSlot=1;else{top+=band+35;colSlot=0;band=0;}}}
 pages.forEach((p,i)=>{const c=p.getContext('2d')!;c.fillStyle=muted;c.font='18px Arial';c.fillText(`Local demonstration · Generated ${generated}`,left,height-78);c.fillText(`Scope ${scope} · ${stateFilter} · Page ${i+1} of ${pages.length}`,left,height-43);});
 const encoder=new TextEncoder(),parts:Uint8Array[]=[],offsets:number[]=[0];let length=0;
 const append=(v:string|Uint8Array)=>{const bytes=typeof v==='string'?encoder.encode(v):v;parts.push(bytes);length+=bytes.length;};
 const object=(id:number,body:string)=>{offsets[id]=length;append(`${id} 0 obj\n${body}\nendobj\n`);};
 append('%PDF-1.4\n');object(1,'<< /Type /Catalog /Pages 2 0 R >>');object(2,`<< /Type /Pages /Count ${pages.length} /Kids [${pages.map((_,i)=>`${3+i*3} 0 R`).join(' ')}] >>`);
 for(let i=0;i<pages.length;i++){const id=3+i*3,imageId=id+2;object(id,`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595.28 841.89] /Resources << /XObject << /Im0 ${imageId} 0 R >> >> /Contents ${id+1} 0 R >>`);const content='q 595.28 0 0 841.89 0 0 cm /Im0 Do Q\n';object(id+1,`<< /Length ${encoder.encode(content).length} >>\nstream\n${content}endstream`);const jpg=await new Promise<Blob>((resolve,reject)=>pages[i].toBlob(b=>b?resolve(b):reject(new Error('PDF page could not be rendered.')),'image/jpeg',0.94));const bytes=new Uint8Array(await jpg.arrayBuffer());offsets[imageId]=length;append(`${imageId} 0 obj\n<< /Type /XObject /Subtype /Image /Width ${width} /Height ${height} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${bytes.length} >>\nstream\n`);append(bytes);append('\nendstream\nendobj\n');}
 const xref=length;append(`xref\n0 ${offsets.length}\n0000000000 65535 f \n`);for(let i=1;i<offsets.length;i++)append(`${String(offsets[i]).padStart(10,'0')} 00000 n \n`);append(`trailer\n<< /Size ${offsets.length} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF\n`);return new Blob(parts.map(p=>p.buffer as ArrayBuffer),{type:'application/pdf'});
}
