import { useEffect, useRef, useState, type FormEvent } from 'react';
import type { SharedDemoSession } from './sharedDemo';
import { USER_LEARNER_ID } from './userDemo';
import { uid } from './store';
import { demoDate } from './administratorMetrics';
import { learnerProgress, learnerScorecard, type OutcomeInput, type OutcomeUpdate, type SupportOutcome, type GrantOutcome, type FollowUpOutcome } from './scorecardDemo';
import { canAcknowledge } from './scorecardValidation';
import './scorecard.css';
export type ScorecardCallbacks = { onOutcome: (input: OutcomeInput) => string | undefined; onReceipt: (updateId: string, note: string) => string | undefined };
const money = (amount: number) => new Intl.NumberFormat('en-NG', { style: 'currency', currency: 'NGN' }).format(amount);
const today = () => new Date().toISOString().slice(0, 10);
export function LearnerScorecard({ session, editable = false, canReceive = false, onOutcome, onReceipt }: { session: SharedDemoSession; editable?: boolean; canReceive?: boolean } & Partial<ScorecardCallbacks>) {
 const score = learnerScorecard(session), [notice,setNotice]=useState(''), [error,setError]=useState(''), feedback=useRef<HTMLParagraphElement>(null);
 useEffect(()=>{if(error)feedback.current?.focus();},[error]);
 const metrics = [['Completed / enrolled',`${score.completed} / ${score.enrolled}`],['Course completion percentage',score.completionRate===null?'No enrolments':`${score.completionRate.toFixed(1)}%`],['Practical work approved',String(score.practicalApproved)],['Practical work pending',String(score.practicalPending)]];
 return <section className="mp-card ms-scorecard" aria-label="Individual learner scorecard"><h3>Individual learner scorecard</h3><p>Learning, support, grants and follow-up are separate records. All outcomes are simulated locally; staff entries and User acknowledgements do not verify actual delivery or trigger payments.</p><div className="ms-metrics">{metrics.map(([label,value])=><div key={label}><p>{label}</p><strong>{value}</strong></div>)}</div><p>{score.completed} completed of {score.enrolled} recorded enrolments. Completion still requires all lessons, best quiz at least 70%, submitted practical work and explicit sample trainer approval. Foundation completion does not establish observed trade competence.</p>
 <p role="status">{notice}</p>{error&&<p role="alert" className="mp-error" ref={feedback} tabIndex={-1}>{error}</p>}
 <h4>Support provision and receipt</h4>{!score.supportRecorded?<p>Support provision not recorded. A reviewed plan does not establish delivery.</p>:<p>{score.supportProvided} staff-recorded provisions · {score.supportReceiptConfirmed} current revisions acknowledged by User.</p>}
 <h4>Grants recorded in NGN</h4>{!score.grantsRecorded?<p>Grant application, award and payment not recorded.</p>:<p>Applied {money(score.grantAppliedNGN)} · Awarded {money(score.grantAwardedNGN)} · Staff-recorded cumulative paid {money(score.grantPaidNGN)} · {score.grantReceiptConfirmed} current payment revisions acknowledged by User.</p>}
 <h4>Follow-up</h4>{!score.followUpsRecorded?<p>Follow-up not recorded.</p>:<p>{score.followUpsOpen} open or in progress of {score.followUpsRecorded} recorded follow-ups.</p>}
 {score.outcomes.map(u=><OutcomeCard key={u.id} session={session} update={u} canReceive={canReceive} onReceipt={(id,note)=>{const message=onReceipt?.(id,note)??(onReceipt?undefined:'Receipt action is unavailable.');setError(message??'');if(!message)setNotice('Receipt acknowledgement recorded for this revision.');return message;}} />)}
 {editable&&onOutcome&&<OutcomeEditor session={session} onOutcome={input=>{const message=onOutcome(input);setError(message??'');if(!message)setNotice('Simulated outcome recorded. Existing evidence and learning gates are preserved.');return message;}} />}
 </section>;
}
function OutcomeCard({session,update:u,canReceive,onReceipt}:{session:SharedDemoSession;update:OutcomeUpdate;canReceive:boolean;onReceipt:(id:string,note:string)=>string|undefined}) {
 const receipt=session.outcomes?.receipts.find(r=>r.updateId===u.id), previous=session.outcomes?.receipts.filter(r=>session.outcomes?.updates.some(old=>old.id===r.updateId&&old.recordId===u.recordId)).at(-1), [note,setNote]=useState('');
 const p=u.payload; const history=session.outcomes?.updates.filter(old=>old.recordId===u.recordId)??[];
 return <article className="ms-outcome"><p className="eyebrow">{u.kind==='follow-up'?'FOLLOW-UP':`${u.kind.toUpperCase()} · SIMULATED RECORD`}</p><h4>{p.title}</h4><p>Recorded by {u.reviewer} · {demoDate(u.at)}</p>
 {u.kind==='support'&&<><p><strong>{u.payload.status==='provided'?'Staff recorded support provided':'Support recorded as not provided'}</strong>{u.payload.providedDate&&` · Provision date ${u.payload.providedDate}`}</p>{(()=>{const snapshot=session.submissions.find(s=>s.id===u.payload.submissionId),item=(snapshot?.payload as {items?:{id:string;need:string}[]})?.items?.find(i=>i.id===u.payload.itemId),latest=session.submissions.filter(s=>s.kind==='support').at(-1);return <p>Submitted support checklist revision {snapshot?.revision}: {item?.need??'Item not available'}{latest?.id!==snapshot?.id?' · Earlier request revision; newer checklist has separate evidence.':''}</p>;})()}</>}
 {u.kind==='grant'&&<><p><strong>Grant {u.payload.stage} recorded</strong> · Applied {money(u.payload.appliedAmount)} · Awarded {money(u.payload.awardedAmount)} · Cumulative paid {money(u.payload.paidAmount)}</p><p>Application date {u.payload.applicationDate}{u.payload.awardDate&&` · Award date ${u.payload.awardDate}`}{u.payload.paymentDate&&` · Payment date ${u.payload.paymentDate}`}</p></>}
 {u.kind==='follow-up'&&<><p><strong>{u.payload.status}</strong> · Owner {u.payload.owner} · Due {u.payload.dueDate}{u.payload.completedDate&&` · Closed ${u.payload.completedDate}`}</p><p className="mp-work">{u.payload.action}</p></>}
 {canAcknowledge(u.kind,p)&&<><p><strong>{receipt?'User acknowledged receipt for this revision':'User receipt not confirmed for this revision'}</strong>{!receipt&&previous?' · An earlier revision was acknowledged.':''}</p>{receipt&&<p>{demoDate(receipt.at)}</p>}{canReceive&&!receipt&&<form onSubmit={e=>{e.preventDefault();onReceipt(u.id,note);}}><label className="mp-field">Receipt acknowledgement for {p.title}<textarea aria-label={`Receipt acknowledgement for ${p.title}`} value={note} onChange={e=>setNote(e.target.value)} required maxLength={5000} rows={2}/></label><button type="submit">Confirm I received {p.title}</button><p>Confirm only the provision/payment displayed in this current simulated record. This does not verify a real transaction.</p></form>}</>}
 <details><summary>Evidence, references and update history ({history.length})</summary>{u.kind!=='follow-up'&&<><p>Reference: {u.payload.reference??'Not recorded'}</p><p className="mp-work">{u.payload.evidence??'Evidence not recorded'}</p></>}{history.map(old=><div key={old.id}><p>{demoDate(old.at)} · {old.reviewer} · {old.reason}</p><OutcomeHistory update={old} /></div>)}{session.outcomes?.receipts.filter(r=>history.some(old=>old.id===r.updateId)).map(r=><p key={r.id}>User receipt acknowledgement · {demoDate(r.at)} · {r.note}{r.updateId===u.id?' · Current revision':' · Earlier revision'}</p>)}</details>
 </article>;
}
function OutcomeHistory({update:u}:{update:OutcomeUpdate}) {
 if(u.kind==='support')return <><p>{u.payload.status==='provided'?'Staff recorded provided':'Not provided'}{u.payload.providedDate&&` · ${u.payload.providedDate}`}</p><p>Reference: {u.payload.reference??'Not recorded'}</p><p className="mp-work">{u.payload.evidence??'Evidence not recorded'}</p></>;
 if(u.kind==='grant')return <><p>{u.payload.stage} · Applied {money(u.payload.appliedAmount)} · Awarded {money(u.payload.awardedAmount)} · Cumulative paid {money(u.payload.paidAmount)}</p><p>Application {u.payload.applicationDate}{u.payload.awardDate&&` · Award ${u.payload.awardDate}`}{u.payload.paymentDate&&` · Payment ${u.payload.paymentDate}`}</p><p>Reference: {u.payload.reference}</p><p className="mp-work">{u.payload.evidence}</p></>;
 return <><p>{u.payload.status} · Owner {u.payload.owner} · Due {u.payload.dueDate}{u.payload.completedDate&&` · Closed ${u.payload.completedDate}`}</p><p className="mp-work">{u.payload.action}</p></>;
}
type FormValues={title:string;status:string;providedDate:string;reference:string;evidence:string;itemId:string;applicationDate:string;awardDate:string;paymentDate:string;appliedAmount:string;awardedAmount:string;paidAmount:string;owner:string;dueDate:string;action:string;completedDate:string;reason:string;reviewer:string};
const blank=():FormValues=>({title:'',status:'not-provided',providedDate:today(),reference:'',evidence:'',itemId:'',applicationDate:today(),awardDate:today(),paymentDate:today(),appliedAmount:'0',awardedAmount:'0',paidAmount:'0',owner:'',dueDate:today(),action:'',completedDate:today(),reason:'',reviewer:'Demo administrator'});
function OutcomeEditor({session,onOutcome}:{session:SharedDemoSession;onOutcome:(input:OutcomeInput)=>string|undefined}) {
 const [kind,setKind]=useState<OutcomeInput['kind']>('support'),[selection,setSelection]=useState('new'),[recordId,setRecordId]=useState<string>(uid),[expected,setExpected]=useState<string>(),[values,setValues]=useState(blank),[supportSnapshotId,setSupportSnapshotId]=useState(()=>session.submissions.filter(s=>s.kind==='support').at(-1)?.id??'');
 const current=learnerScorecard(session).outcomes.filter(u=>u.kind===kind), snapshot=session.submissions.find(s=>s.id===supportSnapshotId),items=(snapshot?.payload as {items?:{id:string;need:string}[]})?.items??[];
 const field=(name:keyof FormValues,label:string,type='text',required=true)=> <label className="mp-field">{label}{type==='textarea'?<textarea aria-label={label} value={values[name]} maxLength={5000} rows={3} required={required} onChange={e=>setValues(v=>({...v,[name]:e.target.value}))}/>:<input aria-label={label} value={values[name]} type={type} required={required} maxLength={type==='text'?250:undefined} min={type==='number'?0:undefined} step={type==='number'?'0.01':undefined} onChange={e=>setValues(v=>({...v,[name]:e.target.value}))}/>}</label>;
 function choose(id:string,newKind=kind){setSupportSnapshotId(session.submissions.filter(s=>s.kind==='support').at(-1)?.id??'');setKind(newKind);setSelection(id);const u=current.find(u=>u.recordId===id&&u.kind===newKind);setRecordId(u?.recordId??uid());setExpected(u?.id);if(u?.kind==='support')setSupportSnapshotId(u.payload.submissionId);if(!u){setValues({...blank(),status:newKind==='grant'?'application':newKind==='follow-up'?'open':'not-provided'});return;}const p=u.payload;setValues({...blank(),...Object.fromEntries(Object.entries(p).map(([k,v])=>[k,String(v)])),status:u.kind==='grant'?u.payload.stage:u.payload.status,reason:'',reviewer:u.reviewer});}
 function submit(e:FormEvent){e.preventDefault();const common={recordId,learnerId:USER_LEARNER_ID,expectedUpdateId:expected,reason:values.reason,reviewer:values.reviewer};const amount=(v:string)=>v.trim()?Number(v):NaN;let input:OutcomeInput;
  if(kind==='support'){const payload:SupportOutcome={title:values.title,submissionId:snapshot?.id??'',itemId:values.itemId,status:values.status as SupportOutcome['status'],...(values.status==='provided'?{providedDate:values.providedDate,reference:values.reference,evidence:values.evidence}:{})};input={...common,kind,payload};}
  else if(kind==='grant'){const stage=values.status as GrantOutcome['stage'],payload:GrantOutcome={title:values.title,stage,appliedAmount:amount(values.appliedAmount),awardedAmount:amount(values.awardedAmount),paidAmount:amount(values.paidAmount),applicationDate:values.applicationDate,reference:values.reference,evidence:values.evidence,...(stage!=='application'?{awardDate:values.awardDate}:{}),...(stage==='paid'?{paymentDate:values.paymentDate}:{})};input={...common,kind,payload};}
  else {const payload:FollowUpOutcome={title:values.title,owner:values.owner,dueDate:values.dueDate,action:values.action,status:values.status as FollowUpOutcome['status'],...(values.status==='closed'?{completedDate:values.completedDate}:{})};input={...common,kind,payload};}
  if(!onOutcome(input)){setSelection('new');setRecordId(uid());setExpected(undefined);setValues({...blank(),status:kind==='grant'?'application':kind==='follow-up'?'open':'not-provided'});}
 }
 return <details className="ms-editor"><summary>Record or update a simulated outcome</summary><p>Administrator records evidence; User confirms receipt separately. Every save appends a revision. Practical approval remains a trainer action.</p><form onSubmit={submit}><div className="ms-form-grid"><label className="mp-field">Outcome type<select aria-label="Outcome type" value={kind} onChange={e=>choose('new',e.target.value as typeof kind)}><option value="support">Support provision</option><option value="grant">Grant recording</option><option value="follow-up">Follow-up</option></select></label><label className="mp-field">Record to update<select aria-label="Record to update" value={selection} onChange={e=>choose(e.target.value)}><option value="new">New outcome record</option>{current.map(u=><option key={u.recordId} value={u.recordId}>{u.payload.title}</option>)}</select></label>{field('title','Outcome title')}
 {kind==='support'&&<><label className="mp-field">Support request item<select aria-label="Support request item" value={values.itemId} disabled={selection!=='new'} required onChange={e=>setValues(v=>({...v,itemId:e.target.value}))}><option value="">Choose a submitted need</option>{items.map(i=><option key={i.id} value={i.id}>{i.need}</option>)}</select></label><label className="mp-field">Support provision status<select aria-label="Support provision status" value={values.status} onChange={e=>setValues(v=>({...v,status:e.target.value}))}><option value="not-provided">Not provided</option><option value="provided">Staff recorded provided</option></select></label>{selection==='new'&&supportSnapshotId!==session.submissions.filter(s=>s.kind==='support').at(-1)?.id&&<p>Support checklist changed. <button type="button" onClick={()=>{setSupportSnapshotId(session.submissions.filter(s=>s.kind==='support').at(-1)?.id??'');setValues(v=>({...v,itemId:''}));}}>Review latest support checklist</button></p>}{selection!=='new'&&<p>This outcome keeps its original checklist item. Use a new outcome for a newer submitted need.</p>}{!items.length&&<p>Submit a support checklist in User before recording provision.</p>}{values.status==='provided'&&field('providedDate','Support provision date','date')}</>}
 {kind==='grant'&&<><label className="mp-field">Grant stage<select aria-label="Grant stage" value={values.status} onChange={e=>setValues(v=>({...v,status:e.target.value,...(e.target.value==='application'?{awardedAmount:'0',paidAmount:'0'}:e.target.value==='awarded'?{paidAmount:'0'}:{})}))}><option value="application">Application recorded</option><option value="awarded">Award recorded</option><option value="paid">Payment recorded</option></select></label>{field('applicationDate','Grant application date','date')}{field('appliedAmount','Grant applied amount (NGN)','number')}{field('awardedAmount','Grant awarded amount (NGN)','number')}{field('paidAmount','Grant cumulative paid amount (NGN)','number')}{values.status!=='application'&&field('awardDate','Grant award date','date')}{values.status==='paid'&&field('paymentDate','Grant payment date','date')}<p>Payment is a staff-entered simulated record. No money moves through this app.</p></>}
 {kind==='follow-up'&&<>{field('owner','Follow-up owner')}{field('dueDate','Follow-up due date','date')}{field('action','Follow-up action','textarea')}<label className="mp-field">Follow-up status<select aria-label="Follow-up status" value={values.status} onChange={e=>setValues(v=>({...v,status:e.target.value}))}><option value="open">Open</option><option value="in-progress">In progress</option><option value="closed">Closed</option></select></label>{values.status==='closed'&&field('completedDate','Follow-up completion date','date')}</>}
 {(kind==='grant'||(kind==='support'&&values.status==='provided'))&&<>{field('reference',kind==='grant'?'Grant reference':'Support reference')}{field('evidence','Evidence description','textarea')}</>}{field('reviewer','Recorded by')}{field('reason','Reason for this update','textarea')}</div>{selection!=='new'&&<button type="button" onClick={()=>choose(selection)}>Refresh selected outcome revision</button>}<button className="primary" type="submit">Save simulated outcome</button></form></details>;
}
export function LearnerProgress({session,onOpenScorecard}:{session:SharedDemoSession;onOpenScorecard:()=>void}) {
 const [threshold,setThreshold]=useState('50'),[filter,setFilter]=useState('all'),[search,setSearch]=useState('');const parsed=threshold.trim()?Number(threshold):NaN,result=learnerProgress(session,parsed);const rows=result.rows.filter(r=>(filter==='all'||r.classification===filter)&&[r.name,r.state,r.lga].join(' ').toLowerCase().includes(search.trim().toLowerCase()));
 return <><p>Choose a follow-up threshold for each learner’s completed/enrolled percentage. It does not change quiz pass marks or completion gates. No enrolments has no percentage and stays separate.</p><div className="ma-filters"><label>Follow-up completion threshold (%)<input type="number" min="0" max="100" step="any" value={threshold} onChange={e=>setThreshold(e.target.value)}/></label><label>Learner completion group<select aria-label="Learner completion group" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All learners</option><option value="below">Below threshold</option><option value="at-or-above">At or above threshold</option><option value="no-enrolments">No enrolments / no learning evidence</option></select></label><label>Search learner progress<input type="search" value={search} onChange={e=>setSearch(e.target.value)}/></label></div>{result.error&&<p role="alert" className="mp-error">{result.error}</p>}<p role="status">{rows.length} learner progress records shown.</p>{!rows.length&&<p>No matching learner progress records.</p>}<div className="ms-progress-list">{rows.map(r=><article className="mp-card" key={r.id}><h3>{r.name}</h3><p>{r.source==='sample'?'Fictional geographic sample · no learning evidence':'User learner'} · {[r.lga,r.state].filter(Boolean).join(', ')||'Location not recorded'}</p><p><strong>{r.completionRate===null?'No enrolments':`${r.completionRate.toFixed(1)}% · ${r.classification==='below'?'Below threshold':'At or above threshold'}`}</strong> · {r.completed} completed of {r.enrolled} enrolled · {r.practicalPending} practical assessments pending</p>{r.outcomes.filter(u=>u.kind==='follow-up').length?r.outcomes.filter(u=>u.kind==='follow-up').map(u=><p key={u.id}>{u.payload.status} · Owner {u.payload.owner} · Due {u.payload.dueDate} · {u.payload.action}</p>):<p>Follow-up not recorded.</p>}{r.source==='user'&&<button onClick={onOpenScorecard}>Open scorecard: {r.name}</button>}</article>)}</div><p>Denominator: this learner’s recorded enrolments. Completed means every lesson, best quiz ≥70%, submitted practical work and explicit sample trainer approval. Geographic samples never enter the User learning denominator.</p></>;
}
