import test from 'node:test';
import assert from 'node:assert/strict';
import { freshSharedDemo, updateSharedDemo, saveSharedDemo, loadSharedDemo, resetSharedDemo, USER_DEMO_BACKUP_KEY } from './sharedDemo';
import { USER_DEMO_KEY, USER_LEARNER_ID, syncLearner, submitWork, submitSupport, submitTeaching } from './userDemo';
import { enrol, updateEnrolment } from './store';
import { decideReview, reviewRecord } from './reviewDemo';
import { buildDemoExport, filterDemoEvents, learnerRows, loadSampleCohort, reportMetrics } from './reportingDemo';
function learner() { const s = freshSharedDemo(); return updateSharedDemo(s, syncLearner({ ...s.user, onboarded: true, profile: { ...s.user.profile, name: 'Named learner', state: 'Plateau', lga: 'Jos North' } })); }
function storage(run: (data: Map<string, string>) => void) { const descriptor = Object.getOwnPropertyDescriptor(globalThis, 'sessionStorage'), data = new Map<string, string>([['mosaic-v1', 'separate sandbox']]); Object.defineProperty(globalThis, 'sessionStorage', { configurable: true, value: { getItem: (k: string) => data.get(k) ?? null, setItem: (k: string, v: string) => data.set(k, v), removeItem: (k: string) => data.delete(k) } }); try { run(data); } finally { if (descriptor) Object.defineProperty(globalThis, 'sessionStorage', descriptor); else Reflect.deleteProperty(globalThis, 'sessionStorage'); } }
test('report counts have exact User enrolment denominator and samples have no learning evidence', () => {
  let s = learner(), d = s.user; const [a, b] = d.learning.courses; d.learning = enrol(enrol(d.learning, USER_LEARNER_ID, a.id), USER_LEARNER_ID, b.id); const [ea, eb] = d.learning.enrolments; d = submitWork(d, ea.id, 'First evidence'); d.learning = updateEnrolment(d.learning, ea.id, { lessons: a.lessons.map((_, i) => i), scores: [70], approved: true }); d = submitWork(d, eb.id, 'Pending evidence'); d.learning.requests.push({ id: 'question', learnerId: USER_LEARNER_ID, courseId: a.id, kind: 'question', text: 'Question', createdAt: Date.now() }, { id: 'message', learnerId: USER_LEARNER_ID, courseId: a.id, kind: 'message', text: 'Message', createdAt: Date.now() }); s = updateSharedDemo(s, d);
  const before = reportMetrics(s, 'user'); assert.equal(before.namedLearners, 1); assert.equal(before.profileReady, 1); assert.equal(before.enrolments, 2); assert.equal(before.completed, 1); assert.equal(before.completionNumerator, 1); assert.equal(before.completionDenominator, 2); assert.equal(before.completionRate, 50); assert.equal(before.pendingPractical, 1); assert.equal(before.unansweredQuestions, 1); assert.equal(before.publishedCourses, 8);
  s = loadSampleCohort(s); const all = reportMetrics(s); assert.equal(all.namedLearners, 6); assert.equal(all.profileReady, 4); assert.equal(all.userLearners, 1); assert.equal(all.sampleLearners, 5); assert.equal(all.completionRate, 50); assert.equal(all.completionDenominator, 2); assert.deepEqual(reportMetrics(s, 'user'), before);
  const samples = reportMetrics(s, 'samples'); assert.equal(samples.namedLearners, 5); assert.equal(samples.profileReady, 3); for (const key of ['enrolments', 'completed', 'pendingPractical', 'unansweredQuestions', 'supportPending', 'teachingPending', 'roster', 'publishedCourses', 'completionNumerator', 'completionDenominator'] as const) assert.equal(samples[key], 0); assert.equal(samples.completionRate, null);
  const empty = reportMetrics(freshSharedDemo()); assert.equal(empty.namedLearners, 0); assert.equal(empty.completionRate, null);
});
test('report pending queues track latest immutable review status rather than existence of a submitted request', () => {
  let s = learner(); s = updateSharedDemo(s, submitSupport({ ...s.user, support: [{ id: 'need', need: 'Device', available: 'Shared device', priority: 'High' }] })); s = updateSharedDemo(s, submitTeaching(s.user, { route: 'experience', skill: 'Skill', examples: 'Examples', explanation: 'Explanation', accessibility: 'Text' }).demo); assert.equal(reportMetrics(s).supportPending, 1); assert.equal(reportMetrics(s).teachingPending, 1);
  const support = reviewRecord(s, 'support')!, teaching = reviewRecord(s, 'teaching')!; s = decideReview(s, { kind: 'support', submissionId: support.submission.id, expectedRevision: support.submission.revision, outcome: 'plan-reviewed', reason: 'Review only', reviewer: 'Demo administrator' }).session; s = decideReview(s, { kind: 'teaching', submissionId: teaching.submission.id, expectedRevision: teaching.submission.revision, outcome: 'approved', reason: 'Review only', reviewer: 'Demo administrator', checklist: { skill: true, examples: true, explanation: true, accessibility: true } }).session; const counts = reportMetrics(s); assert.equal(counts.supportPending, 0); assert.equal(counts.teachingPending, 0); assert.equal(counts.roster, 1); assert.equal(reportMetrics(s, 'samples').roster, 0);
});
test('explicit cohort load is idempotent and preserves User, reviews, catalogue and all existing evidence', () => {
  const s = learner(), previous = structuredClone(s); const next = loadSampleCohort(s); assert.deepEqual(s, previous); assert.deepEqual(next.user, s.user); assert.deepEqual(next.reviews, s.reviews); assert.deepEqual(next.coordination, s.coordination); assert.deepEqual(next.submissions, s.submissions); assert.equal(next.events.length, s.events.length + 1); assert.equal(next.events.at(-1)!.kind, 'sample-cohort-loaded'); assert.equal(loadSampleCohort(next), next); const rows = learnerRows(next); assert.equal(rows.length, 6); assert.equal(rows[0].source, 'user'); assert.equal(rows[0].fictional, false); assert.equal(rows.filter(r => r.state === 'Plateau' && r.lga === 'Jos North' && r.source === 'sample').length, 2); assert.ok(rows.slice(1).every(r => r.fictional && r.name.includes('fictional sample')));
});
test('safe export excludes sensitive metadata and authored text recursively while explicit optin retains session without binary files', () => {
  let s = learner(); const sentinel = 'SENSITIVE_SENTINEL_946'; s.user.profile.name = sentinel; s.user.profile.contact = sentinel; s.user.profile.disabilityDescription = sentinel; s.user.profile.genderDescription = sentinel; s.user.profile.access = [sentinel]; s.user.profile.state = sentinel; s.user.profile.lga = sentinel; s.user.attachments = [{ id: sentinel, name: sentinel, type: sentinel, size: 123, description: sentinel }]; s.user.profile.portfolioDescription = sentinel; s.user.profile.certificates = sentinel; s.user.learning.courses.push({ ...s.user.learning.courses[0], id: sentinel, title: sentinel, description: sentinel, assignment: sentinel, consultantId: sentinel, skills: [sentinel], lessons: [{ title: sentinel, body: sentinel }], quiz: [{ question: sentinel, options: [sentinel, 'B'], answer: 0 }] }); s.user.support = [{ id: sentinel, need: sentinel, available: sentinel, priority: sentinel }]; s.user.learning.requests.push({ id: sentinel, learnerId: USER_LEARNER_ID, courseId: sentinel, kind: 'question', text: sentinel, createdAt: 1, reply: sentinel }); s.events.push({ id: sentinel, kind: 'unknown', recordId: sentinel, at: 1, actor: sentinel, description: sentinel }); s.submissions.push({ id: sentinel, kind: 'work', recordId: sentinel, revision: 1, submittedAt: 1, recordedAt: 1, payload: { text: sentinel, file: new Blob(['FILE_CONTENT_SENTINEL']), bytes: new Uint8Array([1, 2, 3]) } });
  const safe = JSON.stringify(buildDemoExport(s)); assert.ok(!safe.includes(sentinel)); for (const key of ['attachments', 'recordMetadata', 'submissions', 'events', 'profile', 'location', 'description', 'contact']) assert.ok(!Object.keys(buildDemoExport(s)).includes(key)); assert.ok(!safe.includes('FILE_CONTENT_SENTINEL'));
  const sensitive = buildDemoExport(s, true); assert.equal(sensitive.includeSensitive, true); assert.ok(JSON.stringify(sensitive).includes(sentinel)); assert.ok(!JSON.stringify(sensitive).includes('FILE_CONTENT_SENTINEL')); assert.ok('session' in sensitive); const payload = sensitive.session.submissions.at(-1)!.payload as Record<string, unknown>; assert.equal(payload.file, undefined); assert.equal(payload.bytes, undefined); assert.equal('session' in buildDemoExport(s), false);
});
test('settings save/reload and historical absent settings normalize without migration or User mutation', () => storage(data => {
  const s = loadSampleCohort(learner()); assert.equal(saveSharedDemo(s), true); assert.deepEqual(loadSharedDemo().session, JSON.parse(JSON.stringify(s))); assert.equal(data.get('mosaic-v1'), 'separate sandbox');
  const historical = learner(); delete historical.settings; const raw = JSON.stringify(historical); data.set(USER_DEMO_KEY, raw); data.set(USER_DEMO_BACKUP_KEY, 'existing exact legacy backup'); const loaded = loadSharedDemo(); assert.equal(loaded.recovery, undefined); assert.deepEqual(loaded.session.settings, { sampleLearners: [] }); assert.deepEqual(loaded.session.user, historical.user); assert.deepEqual(loaded.session.events, historical.events); assert.equal(data.get(USER_DEMO_KEY), raw); assert.equal(data.get(USER_DEMO_BACKUP_KEY), 'existing exact legacy backup');
  assert.equal(resetSharedDemo(), true); assert.equal(data.has(USER_DEMO_KEY), false); assert.equal(data.has(USER_DEMO_BACKUP_KEY), false); assert.equal(data.get('mosaic-v1'), 'separate sandbox'); assert.deepEqual(loadSharedDemo().session.settings, { sampleLearners: [] });
}));
test('malformed sample settings and dangling cohort events preserve saved source', () => storage(data => {
  const good = loadSampleCohort(learner()); for (const corrupt of [(s: typeof good) => { s.settings!.sampleLearners[0].id = USER_LEARNER_ID; }, (s: typeof good) => { s.settings!.sampleLearners[1].id = s.settings!.sampleLearners[0].id; }, (s: typeof good) => { s.settings!.sampleLearners[0].fictional = false as true; }, (s: typeof good) => { s.settings!.sampleLearners[0].createdAt = Infinity; }, (s: typeof good) => { s.settings!.sampleLearners[0].onboarded = 'yes' as unknown as boolean; }, (s: typeof good) => { s.settings!.sampleLearners[0].state = 3 as unknown as string; }, (s: typeof good) => { delete s.settings!.cohortLoadedAt; }, (s: typeof good) => { s.events = s.events.filter(e => e.kind !== 'sample-cohort-loaded'); }, (s: typeof good) => { delete s.recordMetadata['settings:demo-settings']; }]) { const invalid = structuredClone(good); corrupt(invalid); const raw = JSON.stringify(invalid); data.set(USER_DEMO_KEY, raw); assert.ok(loadSharedDemo().recovery); assert.equal(saveSharedDemo(good), false); assert.equal(data.get(USER_DEMO_KEY), raw); }
}));
test('event date filters use inclusive UTC calendar bounds and reject invalid or reversed ranges', () => {
  const s = freshSharedDemo(), at = Date.parse('2026-10-08T00:00:00Z'); s.events = [at - 1, at, at + 86399999, at + 86400000].map((time, i) => ({ id: String(i), at: time, kind: i % 2 ? 'course-assigned' : 'work-submitted', actor: i % 2 ? 'administrator' : 'user', recordId: 'record', description: 'Description' })); assert.deepEqual(filterDemoEvents(s, { from: '2026-10-08', to: '2026-10-08' }).map(e => e.id), ['1', '2']); assert.deepEqual(filterDemoEvents(s, { from: '2026-10-08', to: '2026-10-08', actor: 'administrator' }).map(e => e.id), ['1']); assert.equal(filterDemoEvents(s, { kind: 'work-submitted' }).length, 2); assert.equal(filterDemoEvents(s).length, 4); assert.deepEqual(filterDemoEvents(s, { from: '2026-02-30' }), []); assert.deepEqual(filterDemoEvents(s, { from: '2026-10-09', to: '2026-10-08' }), []);
});
