import test from 'node:test';
import assert from 'node:assert/strict';
import { freshSharedDemo, updateSharedDemo, loadSharedDemo, saveSharedDemo, resetSharedDemo } from './sharedDemo';
import { USER_LEARNER_ID, USER_DEMO_KEY, syncLearner, submitSupport, submitWork } from './userDemo';
import { enrol, updateEnrolment } from './store';
import { recordOutcome, acknowledgeOutcome, learnerScorecard, learnerProgress, latestOutcomes, type OutcomeInput, type GrantOutcome } from './scorecardDemo';
import { buildDemoExport, loadSampleCohort } from './reportingDemo';
import { decideReview, reviewRecord } from './reviewDemo';
function learner() { const s=freshSharedDemo();return updateSharedDemo(s,syncLearner({...s.user,signedIn:true,onboarded:true,profile:{...s.user.profile,name:'Scorecard learner',state:'Plateau',lga:'Jos North'},support:[{id:'device',need:'A sample device',available:'Paper',priority:'High'}]})); }
function support() { let s=learner();return updateSharedDemo(s,submitSupport(s.user)); }
function supportInput(s:ReturnType<typeof freshSharedDemo>):Extract<OutcomeInput,{kind:'support'}> { return {recordId:'support-outcome',learnerId:USER_LEARNER_ID,kind:'support',reason:'Staff evidence recorded',reviewer:'Demo staff',payload:{title:'Sample device',submissionId:s.submissions.filter(x=>x.kind==='support').at(-1)!.id,itemId:'device',status:'provided',providedDate:'2026-10-08',reference:'private-reference',evidence:'private delivery description'}}; }
function grantInput():Extract<OutcomeInput,{kind:'grant'}> { return {recordId:'grant-outcome',learnerId:USER_LEARNER_ID,kind:'grant',reason:'Staff entry',reviewer:'Demo staff',payload:{title:'Sample grant',stage:'paid',appliedAmount:1000,awardedAmount:800,paidAmount:300,applicationDate:'2026-10-01',awardDate:'2026-10-02',paymentDate:'2026-10-03',reference:'private-grant-reference',evidence:'private payment description'}}; }
function storage(run:(data:Map<string,string>)=>void) { const descriptor=Object.getOwnPropertyDescriptor(globalThis,'sessionStorage'),data=new Map<string,string>([['mosaic-v1','sandbox']]);Object.defineProperty(globalThis,'sessionStorage',{configurable:true,value:{getItem:(k:string)=>data.get(k)??null,setItem:(k:string,v:string)=>data.set(k,v),removeItem:(k:string)=>data.delete(k)}});try{run(data);}finally{if(descriptor)Object.defineProperty(globalThis,'sessionStorage',descriptor);else Reflect.deleteProperty(globalThis,'sessionStorage');} }
test('scorecard learning denominator and practical gates are independent of recorded outcomes',()=>{
 let s=learner(),d=s.user;const [a,b]=d.learning.courses;d.learning=enrol(enrol(d.learning,USER_LEARNER_ID,a.id),USER_LEARNER_ID,b.id);const [first,second]=d.learning.enrolments;d=submitWork(d,first.id,'Reviewed work');d.learning=updateEnrolment(d.learning,first.id,{lessons:a.lessons.map((_,i)=>i),scores:[70],approved:true});d=submitWork(d,second.id,'Pending work');s=updateSharedDemo(s,d);const score=learnerScorecard(s);assert.equal(score.enrolled,2);assert.equal(score.completed,1);assert.equal(score.completionRate,50);assert.equal(score.practicalApproved,1);assert.equal(score.practicalPending,1);assert.equal(learnerScorecard(learner()).completionRate,null);
 const before=structuredClone(s.user);s=recordOutcome(s,grantInput()).session;assert.deepEqual(s.user,before);assert.equal(learnerScorecard(s).completionRate,50);assert.equal(learnerScorecard(s).supportRecorded,0);assert.equal(learnerScorecard(s).grantPaidNGN,300);
});
test('support reviewed plan never implies delivery; staff provision and User receipt remain distinct and snapshot-linked',()=>{
 let s=support();const review=reviewRecord(s,'support')!;s=decideReview(s,{kind:'support',submissionId:review.submission.id,expectedRevision:review.submission.revision,outcome:'plan-reviewed',reason:'Plan only',reviewer:'Administrator'}).session;assert.equal(learnerScorecard(s).supportRecorded,0);const input=supportInput(s);s=recordOutcome(s,input).session;const u=latestOutcomes(s)[0];assert.equal(learnerScorecard(s).supportProvided,1);assert.equal(learnerScorecard(s).supportReceiptConfirmed,0);assert.ok(acknowledgeOutcome(s,u.id,'').error);s=acknowledgeOutcome(s,u.id,'I received this sample device').session;assert.equal(learnerScorecard(s).supportReceiptConfirmed,1);assert.equal(acknowledgeOutcome(s,u.id,'I received this sample device').session,s);
 const revision={...input,expectedUpdateId:u.id,payload:{...input.payload,evidence:'Revised delivery evidence'}} as OutcomeInput;const old=structuredClone(s.outcomes);s=recordOutcome(s,revision).session;assert.equal(learnerScorecard(s).supportReceiptConfirmed,0);assert.deepEqual(s.outcomes!.receipts,old!.receipts);assert.equal(acknowledgeOutcome(s,u.id,'I received this sample device').session,s);assert.ok(acknowledgeOutcome(s,u.id,'New obsolete note').error);
 const d={...s.user,support:[{id:'new-need',need:'Different equipment',available:'None',priority:'High'}]};s=updateSharedDemo(s,submitSupport(d));const current=latestOutcomes(s)[0]; assert.ok(recordOutcome(s,{...revision,expectedUpdateId:current.id,reason:'Rebind old provision',payload:{...revision.payload,submissionId:s.submissions.filter(x=>x.kind==='support').at(-1)!.id,itemId:'new-need'}} as OutcomeInput).error); const oldUpdate=recordOutcome(s,{...revision,expectedUpdateId:current.id,reason:'Correct original provision evidence'});assert.equal(oldUpdate.error,undefined);s=oldUpdate.session;assert.equal(learnerScorecard(s).supportProvided,1);assert.equal(latestOutcomes(s)[0].kind,'support');assert.notEqual((latestOutcomes(s)[0].payload as {submissionId:string}).submissionId,s.submissions.filter(x=>x.kind==='support').at(-1)!.id);
});
test('outcome append guards prevent replay overwrite and preserve immutable learning/history',()=>{
 let s=support();const first=supportInput(s),before=structuredClone(s.user);s=recordOutcome(s,first).session;const a=latestOutcomes(s)[0],second={...first,expectedUpdateId:a.id,reason:'Revise evidence',payload:{...first.payload,evidence:'Revision B'}} as OutcomeInput;s=recordOutcome(s,second).session;const b=latestOutcomes(s)[0],snapshot=structuredClone(s);assert.equal(recordOutcome(s,first).session,s);assert.deepEqual(s,snapshot);assert.ok(recordOutcome(s,{...second,reason:'Old screen writes C'}).error);assert.equal(latestOutcomes(s)[0].id,b.id);assert.deepEqual(s.user,before);assert.equal(s.recordMetadata['outcome:support-outcome'].revision,2);
 assert.ok(recordOutcome(s,{...first,recordId:'sample-record',learnerId:'sample-jos-1'}).error);assert.ok(recordOutcome(s,{...first,recordId:'sample-record',reason:''}).error);
});
test('grant monetary/date/evidence stages reject invalid values and record only cumulative amounts',()=>{
 let s=learner();const first=grantInput();for(const patch of [{paidAmount:801},{paidAmount:-1},{paidAmount:NaN},{paidAmount:Infinity},{paidAmount:0.001},{paidAmount:0},{awardedAmount:0},{paymentDate:'2026-02-30'},{awardDate:'2026-09-01'},{reference:''},{evidence:''}])assert.ok(recordOutcome(s,{...first,payload:{...first.payload,...patch}} as OutcomeInput).error);
 const p=first.payload as GrantOutcome;assert.ok(recordOutcome(s,{...first,payload:{...p,stage:'application',awardedAmount:0,paidAmount:0}}).error,'application cannot carry award/payment dates');assert.ok(recordOutcome(s,{...first,payload:{...p,stage:'awarded',paidAmount:0,paymentDate:undefined,awardedAmount:0}}).error,'award stage requires a positive award');
 s=recordOutcome(s,first).session;const a=latestOutcomes(s)[0];s=acknowledgeOutcome(s,a.id,'First paid amount received').session;s=recordOutcome(s,{...first,expectedUpdateId:a.id,payload:{...p,paidAmount:500,paymentDate:'2026-10-04'}}).session;assert.equal(learnerScorecard(s).grantPaidNGN,500);assert.equal(learnerScorecard(s).grantAwardedNGN,800);assert.equal(learnerScorecard(s).grantReceiptConfirmed,0);assert.equal(s.outcomes!.updates.length,2);
});
test('follow-up owner/action/status and threshold classifications retain no-enrolment and equality boundaries',()=>{
 let s=loadSampleCohort(learner());const command:OutcomeInput={recordId:'follow-up',learnerId:USER_LEARNER_ID,kind:'follow-up',reviewer:'Staff',reason:'Coordinate',payload:{title:'Learning follow-up',owner:'Demo mentor',dueDate:'2026-10-12',action:'Discuss learning plan',status:'open'}};for(const patch of [{owner:''},{action:''},{dueDate:'2026-02-30'},{status:'closed'}])assert.ok(recordOutcome(s,{...command,payload:{...command.payload,...patch}} as OutcomeInput).error);s=recordOutcome(s,command).session;assert.equal(learnerScorecard(s).followUpsOpen,1);assert.ok(acknowledgeOutcome(s,latestOutcomes(s)[0].id,'Received').error);
 assert.ok(learnerProgress(s,-1).error);assert.ok(learnerProgress(s,101).error);assert.ok(learnerProgress(s,NaN).error);assert.ok(learnerProgress(s,'50' as unknown as number).error);assert.ok(learnerProgress(s).rows.every(r=>r.classification==='no-enrolments'&&r.completionRate===null));
 let d=s.user;const c=d.learning.courses[0];d.learning=enrol(d.learning,USER_LEARNER_ID,c.id);s=updateSharedDemo(s,d);assert.equal(learnerProgress(s,0).rows[0].classification,'at-or-above');assert.equal(learnerProgress(s,50).rows[0].classification,'below');d=submitWork(s.user,d.learning.enrolments[0].id,'Complete');d.learning=updateEnrolment(d.learning,d.learning.enrolments[0].id,{lessons:c.lessons.map((_,i)=>i),scores:[100],approved:true});s=updateSharedDemo(s,d);assert.equal(learnerProgress(s,100).rows[0].classification,'at-or-above');assert.equal(learnerProgress(s,50).rows.filter(r=>r.source==='sample'&&r.classification==='no-enrolments').length,5);
});
test('outcome persistence, absent schema2 normalization, malformed source recovery and reset preserve sandbox',()=>storage(data=>{
 let s=support();s=recordOutcome(s,supportInput(s)).session;s=acknowledgeOutcome(s,latestOutcomes(s)[0].id,'Receipt confirmed').session;s=recordOutcome(s,grantInput()).session;assert.equal(saveSharedDemo(s),true);assert.deepEqual(loadSharedDemo().session,JSON.parse(JSON.stringify(s)));
 for(const corrupt of [(x:typeof s)=>{x.outcomes!.updates[0].payload.title='';},(x:typeof s)=>{(x.outcomes!.updates[0].payload as {submissionId:string}).submissionId='missing';},(x:typeof s)=>{x.outcomes!.updates[1].payload={...(x.outcomes!.updates[1].payload as GrantOutcome),paidAmount:9999};},(x:typeof s)=>{x.outcomes!.receipts[0].updateId='missing';},(x:typeof s)=>{x.events=x.events.filter(e=>e.kind!=='outcome-receipt-confirmed');},(x:typeof s)=>{x.outcomes!.updates[0].expectedUpdateId='missing';}]){const invalid=structuredClone(s);corrupt(invalid);const raw=JSON.stringify(invalid);data.set(USER_DEMO_KEY,raw);assert.ok(loadSharedDemo().recovery);assert.equal(saveSharedDemo(s),false);assert.equal(data.get(USER_DEMO_KEY),raw);}
 const historical=learner();delete historical.outcomes;data.set(USER_DEMO_KEY,JSON.stringify(historical));assert.deepEqual(loadSharedDemo().session.outcomes,{updates:[],receipts:[]});assert.equal(resetSharedDemo(),true);assert.equal(data.get('mosaic-v1'),'sandbox');assert.deepEqual(loadSharedDemo().session.outcomes,{updates:[],receipts:[]});
}));
test('anonymous outcome export contains numeric totals without outcome names, references, actors or text',()=>{
 let s=support(),command=supportInput(s);command={...command,payload:{...command.payload,title:'PRIVATE_OUTCOME_SENTINEL',reference:'PRIVATE_REFERENCE_SENTINEL',evidence:'PRIVATE_EVIDENCE_SENTINEL'},reason:'PRIVATE_REASON_SENTINEL',reviewer:'PRIVATE_ACTOR_SENTINEL'};s=recordOutcome(s,command).session;s=recordOutcome(s,grantInput()).session;s=acknowledgeOutcome(s,latestOutcomes(s)[0].id,'PRIVATE_RECEIPT_SENTINEL').session;const safe=JSON.stringify(buildDemoExport(s));for(const sentinel of ['PRIVATE_','private-reference','private-grant-reference','private payment description','Scorecard learner','support-outcome','grant-outcome'])assert.equal(safe.includes(sentinel),false,sentinel);assert.ok(safe.includes('grantPaidNGN'));const full=buildDemoExport(s,true);assert.ok(JSON.stringify(full).includes('PRIVATE_RECEIPT_SENTINEL'));assert.ok(JSON.stringify(full).includes('private-grant-reference'));
});
test('NGN validation accepts large exact cents, rejects fractions and totals cents exactly',()=>{
 const original=grantInput(), p=original.payload;const large=recordOutcome(learner(),{...original,payload:{...p,appliedAmount:10000000000.03,awardedAmount:10000000000.03,paidAmount:10000000000.03}});assert.equal(large.error,undefined);assert.equal(learnerScorecard(large.session).grantPaidNGN,10000000000.03);assert.ok(recordOutcome(learner(),{...original,payload:{...p,paidAmount:0.001}}).error);
 let s=recordOutcome(learner(),{...original,recordId:'grant-a',payload:{...p,appliedAmount:.1,awardedAmount:.1,paidAmount:.1}}).session;s=recordOutcome(s,{...original,recordId:'grant-b',payload:{...p,appliedAmount:.2,awardedAmount:.2,paidAmount:.2}}).session;assert.equal(learnerScorecard(s).grantPaidNGN,.3);assert.equal(learnerScorecard(s).grantAwardedNGN,.3);
});
