import { sources } from './evidence';
// Presentation metadata is deliberately separate from AI request context.
export const documentarySources = [
 {"id": "leadership", "title": "FMINO: leadership profile", "date": "2024-10-26", "url": "https://fmino.gov.ng/championing-inclusion-chief-ayuba-gufwans-mission-for-persons-with-disabilities-in-nigeria/", "summary": "Profile of Gufwan’s advocacy background and partnership approach; aspirations are not measured outcomes."},
 {"id": "education", "title": "FMINO: UBEC inclusive-education engagement", "date": "2024-09-26", "url": "https://fmino.gov.ng/children-with-disabilities-deserve-more-attention-to-attain-their-aspirations-in-life-ayuba-gufwan/", "summary": "Gufwan advocated for inclusive learning support at UBEC. Partnership discussion, not completed educational provision."},
 {"id": "civic", "title": "FMINO: election-monitoring situation room", "date": "2024-09-21", "url": "https://fmino.gov.ng/persons-with-disabilities-franchise-can-never-be-undermined-gufwan/", "summary": "Gufwan spoke at the Abuja situation room; the report also records polling access barriers and violence."},
 {"id": "enforcement", "title": "FMINO: accessibility and enforcement training", "date": "2025-06-14", "url": "https://fmino.gov.ng/national-commission-for-persons-with-disabilities-organises-capacity-building-training-for-security-agencies-on-accessibility-and-anti-discrimination-enforcement/", "summary": "NCPWD and Nightstone Global training. The report credits Gufwan’s keynote and identifies Ikem Ochigbelam as his representative."},
 {"id": "health", "title": "FMINO: Karonmajiji medical outreach", "date": "2025-12-19", "url": "https://fmino.gov.ng/ncpwd-embarks-on-medical-outreach-treats-over-150-with-various-medical-conditions/", "summary": "Activity on 18 December 2025, reported the following day. Lawrence Idemudia represented Gufwan; development partners supported delivery."},
 {"id": "cbm", "title": "FMINO: CBM partnership engagement", "date": "2024-10-31", "url": "https://fmino.gov.ng/gufwan-visits-christian-blind-mission-to-strengthen-ties-for-inclusivity/", "summary": "Gufwan’s Abuja visit discussed accurate data, coordination and deeper cooperation; subsequent delivery is unverified."},
 {id:'appointment',title:'Presidency appointment announcement',date:'2024-08-06',url:'https://statehouse.gov.ng/president-tinubu-appoints-new-heads-of-agencies-and-programmes-under-the-federal-ministry-of-humanitarian-affairs-disaster-management-and-social-management/',summary:'Ayuba Gufwan’s appointment was announced on 6 August 2024.'},
 {id:'abia',title:'FMINO: Abia regional-access engagement',date:'2025-01-19',url:'https://fmino.gov.ng/gufwan-takes-governor-otti-as-champion-of-the-disabilities-community-in-nigeria/',summary:'Working visit and facility approval for a proposed Southeast office; operation is unverified.'},
 {id:'farm',title:'FMINO: fertilizers and farming tools',date:'2025-07-07',url:'https://fmino.gov.ng/empowering-persons-with-disabilities-in-agriculture-ncpwd-distributes-fertilizers-and-farming-tools/',summary:'Distribution reported. The body contains an inconsistent activity date; publication date is used here.'},
 {id:'mobility',title:'Qualitative Magazine: Otukpo mobility partnership',date:'2025-10-11',url:'https://qualitativemagazine.com/ncpwd-beautiful-gate-foundation-senator-abba-moro-empower-pwds-in-benue-with-thousands-of-tricycles-and-assistive-devices/',summary:'Joint distribution reported with Beautiful Gate and Senator Abba Moro; no verified total or economic outcome asserted here.'},
];
// Further reading stays in presentation metadata; it is not AI request context.
export const leadershipReading = [
 {id:'who-story',title:'WHO: From neglect to inspiration',date:'2019-04-23',url:'https://www.afro.who.int/news/neglect-inspiration-ayuba-gufwans-story',summary:'WHO profiles Gufwan as a polio survivor, mobility advocate and vaccine champion. A historical account of his work before his NCPWD appointment.'},
 {id:'wheels-story',title:'Wheels of Hope: Who is Ayuba?',date:'Not dated',url:'https://www.rotarywheelsofhope.org/blog/who-is-ayuba/',summary:'A partner account of his education, Beautiful Gate and locally built mobility devices. Partner-reported history and totals are not independently verified here.'},
 {id:'beautiful-gate-story',title:'Beautiful Gate: the organisation?s story',date:'Not dated',url:'https://www.beautifulgatewheelchairs.org/',summary:'Beautiful Gate describes the mobility workshop in Jos and its origins with Ayuba Gufwan and Ron Rice. This is the organisation?s own account.'},
 {id:'gufwan-interview',title:'TheCable: Gufwan on inclusion and public priorities',date:'2025-11-15',url:'https://www.thecable.ng/interview-why-we-proposed-allocating-10-of-government-interventions-to-pwds-by-ayuba-gufwan/',summary:'A first-person interview on education, accessibility, disability data and the Commission?s priorities. Statements and proposed initiatives remain attributed to the interview.'},
];
export const sourceRegister = [...documentarySources,...sources,...leadershipReading];
export const sourceFor = (id:string) => sourceRegister.find(s=>s.id===id)!;
export type DocumentaryPhoto = {id:string;path:string;original:string;source:string;date:string;location:string;caption:string;alt:string;credit:string;programme:string;width:number;height:number;gufwanPictured:boolean;identification:string};
export const photos:DocumentaryPhoto[] = [
 {id:'noa',path:'/photos/noa.webp',original:'https://fmino.gov.ng/wp-content/uploads/2025/12/Chief-Ayuba-Gufwan-and-Mallam-Lanre-Issa-Onilu.jpg',source:'outreach',date:'2025-12-10',location:'NOA headquarters, Abuja',caption:'Chief Ayuba Gufwan and NOA Director-General Lanre Issa-Onilu at an inclusion engagement.',alt:'Ayuba Gufwan and Lanre Issa-Onilu seated together, shaking hands at the NOA engagement.',credit:'Photograph published by FMINO',programme:'institutions',width:950,height:633,gufwanPictured:true,identification:'Named by the NOA report caption; Gufwan is on the left.'},
 {id:'farm',path:'/photos/farm.webp',original:'https://fmino.gov.ng/wp-content/uploads/2025/07/Persons-with-Disabilities-in-Agriculture.jpg',source:'farm',date:'2025-07-07',location:'Nigeria; venue not specified in report',caption:'Participants at the Commission’s agricultural-support distribution.',alt:'Participants, including wheelchair users, beside fertilizer sacks and boxes at the agricultural-support activity.',credit:'Photograph published by FMINO',programme:'livelihoods',width:950,height:633,gufwanPictured:false,identification:'Participant activity; no Gufwan identity assigned.'},
 {id:'abia',path:'/photos/abia.webp',original:'https://fmino.gov.ng/wp-content/uploads/2025/01/Governor-Otti-As-Champion-Of-The-Disabilities-Community-In-Nigeria.jpg',source:'abia',date:'2025-01-19',location:'Abia State',caption:'Governor Alex Otti at the partner engagement covered in the regional-access report. Gufwan is not pictured in this frame.',alt:'Governor Alex Otti holding a microphone beside a seated woman at the Abia partner engagement.',credit:'Photograph published by FMINO',programme:'communities',width:950,height:634,gufwanPictured:false,identification:'The published frame depicts Governor Otti and a partner, not Gufwan.'},
 {"id": "leadership", "path": "/photos/leadership.webp", "original": "https://fmicgovng.s3.amazonaws.com/cityhill/wp-content/uploads/2024/10/Chief-Ayuba-Gufwan-696x464.jpg", "source": "leadership", "date": "2024-10-26", "location": "Nigeria; photograph venue not specified", "caption": "Chief Ayuba Gufwan, in the photograph published with FMINO’s leadership profile.", "alt": "Chief Ayuba Gufwan seated at a table, speaking into a microphone.", "programme": "leadership", "credit": "Photograph published by FMINO", "width": 696, "height": 464, "gufwanPictured": true, "identification": "Named in the publisher’s photograph caption; no event date is inferred."},
 {"id": "education-2", "path": "/photos/education-2.webp", "original": "https://fmicgovng.s3.amazonaws.com/cityhill/wp-content/uploads/2024/09/Children-With-Disabilities1.jpg", "source": "education", "date": "2024-09-26", "location": "UBEC, Abuja", "caption": "Gufwan during the UBEC partnership discussion on inclusive education.", "alt": "Gufwan, seated on the right, speaking across a meeting table with a UBEC official.", "programme": "education", "credit": "Photograph published by FMINO", "width": 950, "height": 633, "gufwanPictured": true, "identification": "Article-matched meeting frame, compared with the report’s named Gufwan photograph."},
 {"id": "civic", "path": "/photos/civic.webp", "original": "https://fmicgovng.s3.amazonaws.com/cityhill/wp-content/uploads/2024/09/Gufwan-696x464.jpg", "source": "civic", "date": "2024-09-21", "location": "NCPWD headquarters, Abuja", "caption": "Gufwan speaking during election monitoring at the Commission’s situation room.", "alt": "Chief Ayuba Gufwan holding a microphone and gesturing with an open hand.", "programme": "civic", "credit": "Photograph published by FMINO", "width": 696, "height": 464, "gufwanPictured": true, "identification": "Named by the report’s photograph caption."},
 {"id": "enforcement", "path": "/photos/enforcement.webp", "original": "https://fmino.gov.ng/wp-content/uploads/2025/06/Capacity-Building-Training-for-Security-Agencies-696x463.jpg", "source": "enforcement", "date": "2025-06-14", "location": "Hawthorn Suites, Garki, Abuja", "caption": "Participants at the accessibility and anti-discrimination enforcement training. Individual identities are not assigned in this group frame.", "alt": "Security personnel and other participants, including wheelchair users, posing together in front of a training banner.", "programme": "enforcement", "credit": "Photograph published by FMINO", "width": 696, "height": 463, "gufwanPictured": false, "identification": "Gufwan is not individually verified in this frame; the report records representation by Ikem Ochigbelam."},
 {"id": "health", "path": "/photos/health.webp", "original": "https://fmino.gov.ng/wp-content/uploads/2025/12/NCPWD-Embarks-on-Medical-Outreach-696x927.jpg", "source": "health", "date": "2025-12-19", "location": "Karonmajiji, Abuja", "caption": "Community members and the medical team at the 18 December 2025 outreach. Lawrence Idemudia represented Gufwan.", "alt": "Community members waiting by tables where medical staff provide outreach support.", "programme": "health", "credit": "Photograph published by FMINO", "width": 696, "height": 927, "gufwanPictured": false, "identification": "No Gufwan identity assigned; the report explicitly names his representative."},
 {"id": "cbm", "path": "/photos/cbm.webp", "original": "https://fmicgovng.s3.amazonaws.com/cityhill/wp-content/uploads/2024/11/Gufwan-Visits-Christian-Blind-Mission-To-Strengthen-Ties-For-Inclusivity13-696x464.jpg", "source": "cbm", "date": "2024-10-31", "location": "CBM office, Abuja", "caption": "Gufwan and CBM Country Director Abdulaziz Musa at the partnership engagement.", "alt": "Gufwan, on the right, and CBM’s Abdulaziz Musa holding a publication together at a meeting table.", "programme": "institutions", "credit": "Photograph published by FMINO", "width": 696, "height": 464, "gufwanPictured": true, "identification": "Both are named in the publisher’s photograph caption."},
 {"id": "mobility-2", "path": "/photos/mobility-2.webp", "original": "https://qualitativemagazine.com/wp-content/uploads/2025/10/1000489676-1024x683.jpg", "source": "mobility", "date": "2025-10-11", "location": "Otukpo, Benue State", "caption": "Tricycles pictured in the mobility-support report, delivered through a partnership with Beautiful Gate and Senator Abba Moro.", "alt": "Rows of colourful three-wheeled mobility devices arranged at the Otukpo activity.", "programme": "mobility", "credit": "Photograph published by The Qualitative Magazine", "width": 1024, "height": 683, "gufwanPictured": false, "identification": "This photograph shows devices; no individual identity is assigned."},
];
export const heroPhotos = photos.filter(p => ["noa", "leadership", "cbm"].includes(p.id));
export const achievements = [
 {id:'mobility',title:'Mobility and participation',location:'Otukpo, Benue State',date:'2025-10-11',status:'Reported delivery',source:'mobility',photos:['mobility-2'],account:'A joint mobility-support activity brought tricycles and assistive devices to persons with disabilities in Otukpo.',role:'NCPWD participated in the partnership. Gufwan spoke at the event and commended the collaborators.',partners:'Beautiful Gate Handicapped People Center and Senator Abba Moro.',evidence:'The media report describes distribution. Recipient totals, sustained device use and economic outcomes have not been independently verified here.'},
 {id:'livelihoods',title:'Skills and livelihoods',location:'Nigeria; distribution venue not specified',date:'2025-07-07',status:'Reported delivery',source:'farm',photos:['farm'],account:'The Commission reported distributing fertilizers and basic farming tools to participants organised through disability associations.',role:'Lawrence Idemudia represented the Executive Secretary at the distribution. The wider skills agenda includes an announced Amnesty International collaboration.',partners:'Participating disability associations, including JONAPWD, the Nigerian Association of the Blind and the Nigerian National Association of the Deaf.',evidence:'Published 7 July 2025; the body states 7 June and an inconsistent weekday, so the activity date remains uncertain. No yield or income improvement is established. The separate November skills partnership is proposed collaboration, not completed training.'},
 {"id": "education", "title": "Inclusive education", "location": "UBEC, Abuja", "date": "2024-09-26", "status": "Advocacy and discussion", "source": "education", "photos": ["education-2"], "account": "At UBEC, Gufwan called for learning materials, assistive devices and better access to education for children with disabilities, including girls.", "role": "Gufwan participated in the courtesy visit and advocated for collaboration and support for rural communities.", "partners": "Universal Basic Education Commission and its special-needs team.", "evidence": "The report documents advocacy and partnership discussion. It does not establish that NCPWD provided the proposed materials, opened schools or achieved educational outcomes."},
 {"id": "civic", "title": "Civic participation", "location": "Abuja / Edo and Kwara monitoring", "date": "2024-09-21", "status": "Delivered engagement", "source": "civic", "photos": ["civic"], "account": "The Commission’s situation room monitored participation in the Edo governorship and Kwara local elections. Gufwan spoke to journalists about voting rights.", "role": "Gufwan personally addressed the monitoring activity. NCPWD’s disability desk reported both access support and unresolved barriers.", "partners": "NSCDC disability desk officers; INEC was discussed in the report.", "evidence": "A polling-unit access barrier in Edo required assistance. Violence in one Kwara ward was also reported. Monitoring and reported assistance do not establish universal access or nationwide voting outcomes."},
 {id:'communities',title:'Services closer to communities',location:'Abia State / Southeast Nigeria',date:'2025-01-19',status:'Announced plan',source:'abia',photos:['abia'],account:'During a working visit to Abia, Gufwan advocated for a Southeast zonal office to make the Commission easier to reach.',role:'Gufwan led the appeal for a facility. Governor Alex Otti approved a facility for the proposed office.',partners:'Abia State Government and Governor Alex Otti.',evidence:'The report documents advocacy and facility approval. It does not establish that the office opened or confirm current services. The photograph depicts the partner engagement, not Gufwan.'},
 {"id": "enforcement", "title": "Accessibility and enforcement", "location": "Hawthorn Suites, Garki, Abuja", "date": "2025-06-14", "status": "Reported training", "source": "enforcement", "photos": ["enforcement"], "account": "NCPWD and Nightstone Global organised capacity-building training for security personnel and taskforce officers on accessibility and anti-discrimination enforcement.", "role": "The report attributes a keynote address to Gufwan and also names Director of Compliance and Enforcement Ikem Ochigbelam as his representative.", "partners": "Nightstone Global Ltd, NSCDC personnel and participating stakeholders.", "evidence": "Training and certificate presentation are reported. Personal attendance is not inferred from the keynote attribution or group photograph. Subsequent enforcement activity and barriers resolved remain unverified."},
 {"id": "health", "title": "Health and community outreach", "location": "Karonmajiji, Abuja", "date": "2025-12-19", "status": "Reported delivery", "source": "health", "photos": ["health"], "account": "The Commission reported a medical outreach in Karonmajiji on 18 December 2025, bringing medical support closer to community members.", "role": "Lawrence Edelifo Idemudia, Director of Social Integration, represented Gufwan. The Commission’s Social Integration department supervised the activity.", "partners": "TLM, CHAI, CBM and Sightsavers, identified as development partners in the report.", "evidence": "Published 19 December, describing the previous day’s outreach. Wider medical provision was proposed after this pilot. No independently verified treatment total or longer-term health improvement is asserted here."},
 {id:'institutions',title:'Stronger institutions',location:'Abuja / national coordination',date:'2025-12-10',status:'Delivered engagement',source:'outreach',photos:['noa','cbm'],account:'Gufwan led an engagement with NOA on disability awareness and inclusion. A joint technical committee was announced to coordinate next steps.',role:'Gufwan also visited CBM on 31 October 2024 to discuss accurate disability data and stronger cooperation. NCPWD sought NOA’s outreach capacity. Separately, the May 2026 NDMIS stakeholder workshop documented work toward harmonised disability data.',partners:'Christian Blind Mission; National Orientation Agency; NDMIS stakeholder coordination reported by OSSAP-SNEO.',evidence:'The CBM visit and NOA meeting took place; further CBM cooperation and committee delivery and nationwide coverage remain unverified. The NDMIS workshop is design work, not evidence of a deployed database or a live connection to this demonstration.'},
];
export const milestones = [
 {id:'appointment-2024',date:'2024-08-06',title:'Appointment announced',status:'Appointment',source:'appointment',text:'The Presidency names Ayuba Gufwan as Executive Secretary of NCPWD.'},
 ...achievements.filter(a=>a.id!=='institutions').map(a=>({id:a.id+'-report',date:a.date,title:a.title,status:a.status,source:a.source,text:a.account})),
 {id:'cbm-2024',date:'2024-10-31',title:'CBM partnership engagement',status:'Delivered engagement',source:'cbm',text:'Gufwan discusses accurate data and stronger cooperation with CBM. Subsequent delivery is unverified.'},
 {id:'skills-2025',date:'2025-11-07',title:'Skills partnership proposed',status:'Announced plan',source:'partnership',text:'NCPWD and Amnesty International discuss skills acquisition and inclusion collaboration.'},
 {id:'noa-2025',date:'2025-12-10',title:'NOA inclusion engagement',status:'Delivered engagement',source:'outreach',text:'A courtesy visit connects the inclusion agenda with NOA’s outreach capacity.'},
 {id:'ndmis-2026',date:'2026-05-22',title:'NDMIS workshop reported',status:'Reported output',source:'data',text:'A report describes the 18–20 May stakeholder workshop; deployment remains unverified.'},
].sort((a,b)=>a.date.localeCompare(b.date));
