import type { Course } from "./catalogue";

export const additionalSkillCourses: Course[] = [
  {
    id: "people-workplace",
    title: "People & Workplace Essentials",
    description: "Practise clear communication, collaboration and everyday workplace planning with fictional situations.",
    tag: "People and workplace skills",
    category: "people",
    delivery: "self-paced",
    tools: ["Paper or a text editor; no workplace placement required"],
    outcome: "A reviewed communication example, team plan and personal weekly plan.",
    skills: ["Clear communication", "Collaboration planning", "Time planning", "Problem-solving", "Constructive feedback"],
    status: "published",
    consultantId: "expert-demo",
    lessons: [
      {
        title: "Make your message easy to act on",
        body: "A useful message explains the task, the next action and when it is needed. Use familiar words and ask which format the other person prefers. Listening includes checking what you understood rather than guessing. A short written summary can help everyone remember an agreement. Share only the personal information needed for the task.",
        resource: "Practice: write a fictional message asking a colleague for a task update. Include a clear request and a way to clarify it.",
      },
      {
        title: "Agree how a team will work",
        body: "A team needs a shared goal and clear responsibilities. Break a task into parts, ask what each person can contribute and agree how to report progress. Confirm that the deadline and communication method work for everyone. If a barrier appears, discuss an adjustment early. Asking for support and sharing responsibility are useful contributions to teamwork.",
        resource: "Practice: plan a fictional community event with three roles, one shared deadline and an accessible way to check progress.",
      },
      {
        title: "Build confidence through small steps",
        body: "Confidence can grow from preparing, trying a manageable task and reviewing what happened. Describe a strength with an example instead of claiming you can do everything. Rehearse an introduction in a format that suits you, such as writing or speaking. You can ask for time to think or clarify a question. One difficult attempt does not define your ability.",
        resource: "Practice: draft a short introduction with one strength, an example and one skill you are still learning. Choose a small next step.",
      },
      {
        title: "Plan time with room for change",
        body: "List tasks, estimate their time and identify deadlines. Separate urgent work from work that matters over the longer term. Include breaks, access needs and time for unexpected delays. A plan is an estimate, so compare it with what happens and revise it. Tell a teammate early when a deadline needs discussion rather than quietly making an impossible promise.",
        resource: "Practice: make a fictional weekly plan with three priorities, time estimates, breaks and a backup if one task takes longer.",
      },
      {
        title: "Solve a problem before choosing a fix",
        body: "Describe the problem using facts you can check. Ask who is affected and what a successful result would look like. List two or more options, compare their effort and likely effects, then try a small reversible step. Record the result and adjust if needed. Ask a suitable colleague for help when the problem is outside your responsibility or knowledge.",
        resource: "Practice: a team repeatedly misses a handover. Describe the problem, compare two possible responses and choose a small test with a success check.",
      },
      {
        title: "Give and receive useful feedback",
        body: "Useful feedback describes a specific action, its effect and a possible next step. Focus on the work rather than a person's identity. Ask whether this is a good time to discuss it and offer a private, accessible format. When receiving feedback, clarify an example and agree what to try. If comments are discriminatory or threatening, use the organisation's reporting route or seek a trusted person's support.",
        resource: "Practice: write a respectful response to a fictional late handover, then a reply that asks for clarification and agrees a next step.",
      },
    ],
    quiz: [
      { question: "What makes a task message useful?", options: ["A clear request and next action", "As many difficult words as possible", "Only a greeting", "Private details about everyone"], answer: 0 },
      { question: "A teammate needs a different communication format. What should the team do?", options: ["Exclude the teammate", "Assume their preferred format", "Discuss a workable method together", "Stop sharing updates"], answer: 2 },
      { question: "What is a useful way to build confidence?", options: ["Promise to do every task perfectly", "Prepare a manageable step and review the result", "Avoid all feedback", "Compare yourself with everyone"], answer: 1 },
      { question: "A task will take longer than planned. What is the best next step?", options: ["Hide the delay", "Remove all breaks", "Promise the old deadline anyway", "Discuss the deadline early and revise the plan"], answer: 3 },
      { question: "Which feedback is most useful?", options: ["You are always a bad teammate", "Everyone dislikes your work", "The missing handover note delayed the task; could we use a checklist?", "Nothing can improve"], answer: 2 },
    ],
    assignment: "Use fictional names. Write a clear task message, a three-person team plan and a weekly plan with breaks and a backup. Add a short introduction with a strength and example, compare two responses to a handover problem, and write constructive feedback with an agreed next step. Submit text; no workplace placement is required.",
  },
  {
    id: "sewing-textiles",
    title: "Sewing and Simple Textile Products",
    description: "Plan a simple textile product, materials, quality checks and fictional costs before optional supervised making.",
    tag: "Craft foundation",
    category: "livelihoods",
    delivery: "foundation",
    tools: ["Paper or a text editor for the foundation assignment", "Optional making materials and tool support agreed with a competent trainer"],
    outcome: "A reviewed textile product plan, materials estimate and fictional customer brief; making competence is not assessed here.",
    skills: ["Textile product planning", "Materials estimation", "Material costing", "Quality checklist planning", "Customer brief writing"],
    status: "published",
    consultantId: "expert-demo",
    lessons: [
      {
        title: "Choose a small product and a workable space",
        body: "Choose one simple product idea, such as a fabric storage pouch. Describe its purpose, user and approximate finished size. Plan a comfortable, reachable workspace with space for materials and breaks. Ask about the person's preferred ways to see, handle or describe the plan. This foundation uses paper or text; actual making is optional and should be arranged separately with a competent trainer.",
        resource: "Practice: describe a pouch or another simple textile product, its intended use and two workspace or communication preferences.",
      },
      {
        title: "List materials and support before making",
        body: "A materials list records what the proposed product needs, such as fabric, thread and a closure. Describe important properties, including size, texture and intended use, without assuming every fabric suits every product. A trainer can help check suitability and identify tool, access and supervision needs. You do not need to buy supplies to finish this foundation. Mark uncertain choices as questions to ask.",
        resource: "Practice: make a proposed materials list with quantities, an uncertain choice and one support question for a trainer.",
      },
      {
        title: "Describe dimensions in a paper plan",
        body: "A product plan can be a labelled sketch or a written description. State the units and distinguish the proposed finished size from material dimensions. Joining and finishing may need extra material; record that as an allowance to confirm with a trainer rather than guessing it is universal. A paper plan helps identify missing information before making. Use large labels or a text description if a drawing is difficult to use.",
        resource: "Practice: sketch or describe the planned shape and finished dimensions. List any joining or finishing allowances that still need a trainer's check.",
      },
      {
        title: "Plan the joining and finishing review",
        body: "Joining holds parts together; finishing deals with edges and the final appearance. Suitable methods depend on the product, fabric and equipment. Write what you want the join and finish to achieve, then ask a competent trainer to demonstrate appropriate methods if you choose hands-on practice. This text does not teach machine operation or tool handling. A written process plan completes this lesson without cutting, sewing or owning equipment.",
        resource: "Practice: write a proposed making sequence in broad stages and three questions about joining, finishing and supervised practice.",
      },
      {
        title: "Check the plan and estimate costs",
        body: "A quality checklist compares the planned result with the customer brief. Include dimensions, intended use, appearance and any agreed closure. For a fictional cost estimate, multiply each material quantity by its unit price and add the amounts. State the currency, assumptions and an allowance for uncertain costs. Material cost is not the full selling price: time and other costs need separate consideration.",
        resource: "Practice: list four quality checks and calculate a fictional materials total with stated units and prices. Check one multiplication by hand.",
      },
      {
        title: "Prepare a clear customer brief",
        body: "A brief records what the fictional customer wants, including dimensions, appearance, intended use and a proposed delivery time. Separate confirmed requirements from questions. Describe the evidence honestly: a written plan is a plan, and an unreviewed sample is not proof of competence. Before accepting real work, seek appropriate training and check what you can deliver. Foundation completion records the reviewed planning task, not a sewing qualification.",
        resource: "Practice: write a fictional product brief, a proposed price with assumptions, and the next supervised learning step you would request if interested.",
      },
    ],
    quiz: [
      { question: "What is enough to complete this foundation assignment?", options: ["Owning a sewing machine", "A reviewed written or paper product plan", "Selling a real product", "A claimed professional qualification"], answer: 1 },
      { question: "Which information makes a dimension useful?", options: ["A number with no label", "The colour only", "A labelled measurement and its unit", "A guessed customer preference"], answer: 2 },
      { question: "A joining allowance is uncertain. What should you do?", options: ["Mark it for confirmation with a competent trainer", "Assume it is the same for every product", "Leave every dimension out", "Claim it was tested"], answer: 0 },
      { question: "Two metres of fictional fabric cost 1,500 naira per metre. What is the fabric cost?", options: ["750 naira", "1,500 naira", "2,000 naira", "3,000 naira"], answer: 3 },
      { question: "What does a reviewed textile planning assignment demonstrate?", options: ["Qualification to operate every sewing machine", "Guaranteed sales", "Completion of the planning task", "Observed professional making competence"], answer: 2 },
    ],
    assignment: "Prepare a paper or text plan for a simple textile product. Include its purpose, labelled finished dimensions, materials and quantities, questions for a trainer about allowances and methods, four quality checks, fictional material prices and a checked total, and a fictional customer brief. State one access/support preference and distinguish planned work from any actual making. No fabric, tools, sewing or customer transaction is required.",
  },
  {
    id: "small-space-growing",
    title: "Small-Space Growing and Nursery Basics",
    description: "Plan an accessible growing space, local advice questions, observation records and a fictional resource budget.",
    tag: "Growing foundation",
    category: "livelihoods",
    delivery: "foundation",
    tools: ["Paper or a text editor for the foundation assignment", "Optional growing resources and supervision confirmed with a local competent adviser"],
    outcome: "A reviewed growing layout, observation plan and fictional budget; planting competence and yield are not assessed here.",
    skills: ["Growing layout planning", "Resource budgeting", "Observation planning", "Record keeping", "Local advice preparation"],
    status: "published",
    consultantId: "expert-demo",
    lessons: [
      {
        title: "Choose a goal and describe the space",
        body: "Begin with a modest goal, such as planning a few containers or a small nursery area. Describe the available space, light, water access and how materials could be reached. Check permission to use the site. A sketch or text layout can identify access barriers before any purchase. This foundation is a planning exercise; you can complete it without land, plants or equipment.",
        resource: "Practice: describe a real or fictional small space, your growing goal and two access or support needs.",
      },
      {
        title: "Ask about locally suitable plants",
        body: "Plant suitability depends on local conditions, season, available space and the intended use. Ask a competent local extension adviser or trainer which plants and starting materials suit your plan. Record the source and date of advice and questions still unanswered. A nursery plan also needs to consider how young plants would be labelled and cared for. Treat a suggested plant as a candidate until its needs are checked locally.",
        resource: "Practice: choose a candidate plant for a fictional plan and write five questions for a local adviser, including season and resource needs.",
      },
      {
        title: "Map resources and a reachable layout",
        body: "List proposed containers or beds, suitable growing materials to confirm locally, water access and labels. Plan clear routes and reachable work areas according to the learner's preferences. Record dimensions with units and separate what is already available from what needs support. A layout should make routine observation possible without unnecessary reaching or lifting. Ask a trainer to review practical arrangements before carrying them out.",
        resource: "Practice: create a labelled sketch or text layout and a resource table showing available items, missing items and questions to confirm.",
      },
      {
        title: "Prepare an observation log",
        body: "An observation log can record the date, plant label, visible condition, weather or light notes, and any care agreed with an adviser. Describe what you see before giving a possible explanation. Use consistent wording or a simple recording scale so entries can be compared. For this foundation, practise with fictional observations. If you choose actual planting or care, arrange competent guidance rather than treating an app plan as a practical demonstration.",
        resource: "Practice: make three clearly labelled fictional log entries. Separate visible observations from questions or possible explanations.",
      },
      {
        title: "Recognise when to seek advice",
        body: "A change in leaf colour, growth or moisture is an observation, not a confirmed diagnosis. Record what changed, when it started and which plants are affected. Share the record with a competent local adviser to discuss the next step. Do not guess a chemical treatment or copy an unverified recipe. Keep proposed actions separate from actions actually taken and record the advice you receive.",
        resource: "Practice: draft a message to an adviser about a fictional change. Include dates, observations and questions without claiming a diagnosis.",
      },
      {
        title: "Budget and review before starting",
        body: "A small resource budget lists quantities, unit prices and totals in a stated currency. Include uncertainty about local prices and availability. Review your layout, observation plan and support needs before deciding whether to begin a supervised practical step. A growing plan cannot guarantee harvests, income or grants. Completing this foundation shows the reviewed planning task; it does not certify planting competence or a successful crop.",
        resource: "Practice: calculate a fictional three-item budget, check one total by hand and identify the advice or support needed before actual growing.",
      },
    ],
    quiz: [
      { question: "What should guide the choice of a plant for a small growing space?", options: ["Only an attractive photograph", "A promise of guaranteed profit", "Local conditions, season and checked resource needs", "The same choice for every location"], answer: 2 },
      { question: "What belongs in a useful layout plan?", options: ["Reachable work areas, labelled dimensions and resource needs", "Only an unlabeled shape", "An assumed grant approval", "A guaranteed harvest date"], answer: 0 },
      { question: "Which is an observation rather than a diagnosis?", options: ["The plant definitely needs a chemical treatment", "Three leaves look yellow today", "This is certainly one particular disease", "The harvest will fail"], answer: 1 },
      { question: "Four fictional containers cost 800 naira each. What is their total cost?", options: ["200 naira", "800 naira", "1,600 naira", "3,200 naira"], answer: 3 },
      { question: "What does completing this foundation show?", options: ["Guaranteed crop income", "Observed professional nursery competence", "Completion of a reviewed growing plan", "Automatic approval for farming equipment"], answer: 2 },
    ],
    assignment: "Create a small-space growing plan using a fictional or real space. Submit a labelled layout, a candidate plant and five local-adviser questions, a resource/support table, three explicitly fictional observation entries, a message asking about a change without diagnosing it, and a fictional budget with a checked total. State which information needs local confirmation. No planting, chemical use, equipment purchase or actual yield is required.",
  },
  {
    id: "retail-customer-service",
    title: "Retail and Customer Service Practice",
    description: "Use fictional stock, orders and customer situations to practise records, checked totals and respectful service.",
    tag: "Retail foundation",
    category: "livelihoods",
    delivery: "foundation",
    tools: ["Paper or a text editor; a calculator is optional", "Fictional examples only; no shop placement or payment device required"],
    outcome: "A reviewed fictional stock sheet, order record, cash ledger and customer-service role play.",
    skills: ["Stock record planning", "Order recording", "Checked totals", "Customer communication", "Complaint response planning"],
    status: "published",
    consultantId: "expert-demo",
    lessons: [
      {
        title: "Understand the service task",
        body: "Retail service starts by finding out what the customer needs and what the shop can provide. Ask clear questions and confirm the answer instead of assuming a preference. Know the limits of your role and ask a supervisor when an issue exceeds them. Use fictional people and products for this course. You can complete the foundation without a shop placement, sales or real customer information.",
        resource: "Practice: write a fictional customer's request, two clarifying questions and one issue you would refer to a supervisor.",
      },
      {
        title: "Communicate in a useful format",
        body: "Explain an item's description, price and relevant conditions in plain language. Ask which communication format works for the customer and allow time for questions. Confirm understanding without speaking for the customer or making assumptions about ability. If a product is unavailable, explain honestly and offer only alternatives you can verify. A respectful written role play is enough for this lesson.",
        resource: "Practice: draft a conversation about an unavailable item, including a clear price for a fictional alternative and a check of the customer's preference.",
      },
      {
        title: "Keep stock and order records clear",
        body: "A stock sheet can show item name, opening quantity, items received, items issued and closing quantity. Closing quantity equals opening plus received minus issued when those are the only movements. Use consistent units and investigate a mismatch rather than silently altering a record. An order record should identify the fictional item, quantity, agreed price and status. Collect only customer details needed for the task.",
        resource: "Practice: make a three-item fictional stock sheet and one order record. Label units and flag one mismatch for checking.",
      },
      {
        title: "Check prices, totals and a fictional ledger",
        body: "Multiply quantity by unit price to calculate a line total, then add the lines. If a fictional payment exceeds the total, the difference is the change. Check calculations before recording them. A cash ledger records a dated opening balance, money in, money out and closing balance. This lesson uses fictional amounts; it does not require payment processing, cash handling or a live transaction.",
        resource: "Practice: calculate a fictional two-item order and change, then record three fictional ledger entries and check the closing balance by hand.",
      },
      {
        title: "Respond to a complaint with care",
        body: "Listen to the issue, acknowledge the inconvenience and check the relevant order facts. Explain the available next steps according to the shop's policy and your authority. Do not promise a refund or delivery you cannot approve. Share order information only with people who need it to resolve the issue. Escalate a threatening situation through the workplace's procedure instead of trying to resolve it alone.",
        resource: "Practice: write a response to a fictional wrong-item complaint, identify what you must check and state when a supervisor is needed.",
      },
      {
        title: "Review a service example",
        body: "Review a fictional service task from the request through the record and response. Check whether quantities, prices and status agree across the documents. Ask what was clear and what could be improved, then revise one part. Label a written role play honestly in your portfolio. This foundation records completion of reviewed fictional tasks; workplace competence requires appropriate observation and practice separately.",
        resource: "Practice: assemble your fictional stock, order, ledger and service replies. Explain one check you made and one improvement after feedback.",
      },
    ],
    quiz: [
      { question: "An item is unavailable. What is a useful response?", options: ["Promise it is in stock", "Ignore the customer", "Invent a delivery date", "Explain honestly and discuss verified alternatives"], answer: 3 },
      { question: "Opening stock is 10, received stock is 5 and issued stock is 4. What is closing stock?", options: ["19", "11", "9", "6"], answer: 1 },
      { question: "Two items cost 1,200 naira each and a fictional payment is 3,000 naira. What is the change?", options: ["600 naira", "1,800 naira", "2,400 naira", "4,200 naira"], answer: 0 },
      { question: "A complaint needs a refund outside your authority. What should you do?", options: ["Promise it immediately", "Publish the customer's details", "Check the facts and refer it to the appropriate supervisor", "Delete the order"], answer: 2 },
      { question: "What is an honest portfolio label for this assignment?", options: ["Certified retail manager", "Fictional stock records and written customer-service role play", "Verified real sales results", "Guaranteed workplace competence"], answer: 1 },
    ],
    assignment: "Use fictional products and people throughout. Create a three-item stock sheet with a checked closing quantity, one order record, a two-item price calculation with change, and a three-entry cash ledger with a checked balance. Include written replies for an unavailable item and a complaint, an accessible communication option, a referral to a supervisor and one improvement after review. No actual sale, customer data, workplace placement or payment transaction is required.",
  },
];
